export type StageField = { name: string; label: string; type?: "text" | "date" | "datetime-local" | "number" | "file" | "textarea" | "select" | "checkbox"; required?: boolean; placeholder?: string; options?: string[]; wide?: boolean };

const file: StageField = { name: "fileLookup", label: "File no. / passport / phone", required: true, placeholder: "KSA-26-10482" };
const attachment: StageField = { name: "attachment", label: "Supporting document", type: "file", wide: true };
const remarks: StageField = { name: "remarks", label: "Remarks", type: "textarea", wide: true };

export const stageFields: Record<string, StageField[]> = {
  "Passport Management": [file, { name: "passportNumber", label: "Passport number", required: true }, { name: "passportType", label: "Passport type", type: "select", options: ["Ordinary", "Diplomatic", "Official"] }, { name: "issueDate", label: "Issue date", type: "date", required: true }, { name: "expiryDate", label: "Expiry date", type: "date", required: true }, { name: "issuePlace", label: "Place of issue" }, { name: "issuingAuthority", label: "Issuing authority" }, { name: "nationality", label: "Nationality" }, { name: "verificationStatus", label: "Verification", type: "select", options: ["Pending", "Verified", "Rejected", "Correction Required"] }, attachment, remarks],
  "Passport Entry": [file, { name: "passportNumber", label: "Passport number", required: true }, { name: "passportType", label: "Passport type", type: "select", options: ["Ordinary", "Diplomatic", "Official"] }, { name: "issueDate", label: "Issue date", type: "date", required: true }, { name: "expiryDate", label: "Expiry date", type: "date", required: true }, { name: "issuePlace", label: "Issue place" }, { name: "issuingAuthority", label: "Issuing authority" }, { name: "nationality", label: "Nationality" }, { name: "verificationStatus", label: "Verification", type: "select", options: ["Pending", "Verified", "Rejected"] }, attachment, remarks],
  Medical: [file, { name: "center", label: "Medical center", required: true }, { name: "appointmentDate", label: "Appointment date", type: "date" }, { name: "testDate", label: "Medical/test date", type: "date" }, { name: "reportDate", label: "Report date", type: "date" }, { name: "result", label: "Medical result/status", type: "select", required: true, options: ["Pending for Medical", "Slip Submitted", "Medical Present", "Waiting for Report", "Fit", "Unfit", "Recall", "Medical Done"] }, { name: "expiryDate", label: "Medical expiry", type: "date" }, { name: "responsibleParty", label: "Contact medical responsibility", type: "select", options: ["Office", "Customer", "Agent", "Not Required"] }, { name: "fitCardStatus", label: "Fit card status", type: "select", options: ["Pending", "Updated", "Received", "Not Required"] }, { name: "officeStatus", label: "Office processing status", type: "select", options: ["Pending", "In Process", "Done"] }, { name: "isReMedical", label: "Re-Medical", type: "checkbox" }, { name: "contactMedical", label: "Contact medical", type: "checkbox" }, { name: "medicalSlip", label: "Medical slip collected", type: "checkbox" }, { name: "pictureCollected", label: "Picture collected", type: "checkbox" }, { name: "tenFingerDone", label: "Ten-finger completed", type: "checkbox" }, { name: "termsDone", label: "Terms & conditions completed", type: "checkbox" }, attachment, remarks],
  MOFA: [file, { name: "medicalFitState", label: "Medical fit state", type: "select", options: ["Fit", "Unfit", "Pending"] }, { name: "mofaNumber", label: "MOFA number" }, { name: "submitDate", label: "Submit date", type: "date" }, { name: "doneDate", label: "Done date", type: "date" }, { name: "status", label: "MOFA status", type: "select", required: true, options: ["Pending", "Submitted", "Approved", "Rejected", "Done"] }, { name: "medicalSlipState", label: "Medical slip state", type: "select", options: ["Pending", "Available", "Verified"] }, { name: "isReMofa", label: "Re-MOFA", type: "checkbox" }, { name: "isReMedical", label: "Re-Medical file", type: "checkbox" }, attachment, remarks],
  Takamul: [file, { name: "registrationNumber", label: "Registration number" }, { name: "certificateNumber", label: "Certificate number" }, { name: "examDate", label: "Exam date", type: "date" }, { name: "presentDate", label: "Present date", type: "date" }, { name: "centerDistrict", label: "Center district" }, { name: "doneBy", label: "Takamul done by" }, { name: "visaProfession", label: "Visa profession" }, { name: "takamulProfession", label: "Takamul profession" }, { name: "status", label: "Takamul status", type: "select", required: true, options: ["Pending", "Scheduled", "Present", "Done"] }, { name: "reportStatus", label: "Takamul report status", type: "select", options: ["Pending", "Waiting for Result", "Passed", "Failed", "Certificate Issued"] }, attachment, remarks],
  "KSA Bio Finger": [file, { name: "appointmentDate", label: "Appointment date", type: "datetime-local" }, { name: "presentDate", label: "Present date", type: "date" }, { name: "completedAt", label: "Completion date", type: "date" }, { name: "status", label: "Biometric status", type: "select", required: true, options: ["Pending", "Appointment", "Present", "Done", "Failed"] }, attachment, remarks],
  "Police Clearance": [file, { name: "applicationNumber", label: "Application number" }, { name: "applicationDate", label: "Application date", type: "date" }, { name: "issueDate", label: "Issue date", type: "date" }, { name: "expiryDate", label: "Expiry date", type: "date" }, { name: "result", label: "Result" }, { name: "status", label: "Police status", type: "select", required: true, options: ["Pending", "Applied", "Clear", "Issued", "Rejected", "Done"] }, attachment, remarks],
  "First Payment": [file, { name: "invoiceNo", label: "Invoice number" }, { name: "amount", label: "Amount", type: "number", required: true }, { name: "currency", label: "Currency", placeholder: "BDT", required: true }, { name: "method", label: "Payment method", type: "select", options: ["Cash", "Bank Transfer", "Mobile Banking", "Card"] }, { name: "reference", label: "Transaction/receipt number" }, { name: "collectedAt", label: "Collection date", type: "date" }, { name: "collector", label: "Collector" }, { name: "status", label: "Payment status", type: "select", options: ["PENDING", "PAID", "PARTIAL", "FAILED", "REFUNDED"] }, attachment, remarks],
  "Second Payment": [file, { name: "invoiceNo", label: "Invoice number" }, { name: "amount", label: "Amount", type: "number", required: true }, { name: "currency", label: "Currency", placeholder: "BDT", required: true }, { name: "method", label: "Payment method", type: "select", options: ["Cash", "Bank Transfer", "Mobile Banking", "Card"] }, { name: "reference", label: "Transaction/receipt number" }, { name: "dueDate", label: "Due date", type: "date" }, { name: "collectedAt", label: "Collection date", type: "date" }, { name: "status", label: "Payment status", type: "select", options: ["PENDING", "DUE", "PAID", "OVERDUE", "PARTIAL"] }, attachment, remarks],
  "Pending 2nd Payment": [file, { name: "invoiceNo", label: "Invoice number" }, { name: "amount", label: "Total due", type: "number", required: true }, { name: "paidAmount", label: "Paid amount", type: "number" }, { name: "dueDate", label: "Due date", type: "date", required: true }, { name: "currency", label: "Currency", placeholder: "BDT" }, { name: "status", label: "Status", type: "select", options: ["PENDING", "DUE", "PAID", "OVERDUE", "PARTIAL"] }, remarks],
  "Pre Confirm File": [file, { name: "company", label: "Company", required: true }, { name: "demand", label: "Work / demand" }, { name: "profession", label: "Profession", required: true }, { name: "salary", label: "Salary", type: "number" }, { name: "visaReference", label: "Visa reference" }, { name: "visaQuantity", label: "Visa quantity", type: "number" }, { name: "confirmationDate", label: "Confirmation date", type: "date" }, { name: "status", label: "Status", type: "select", options: ["Pending", "Pre-Confirmed", "Approved", "Rejected", "Cancelled"] }, remarks],
  "Approval Application": [file, { name: "applicationNumber", label: "Application number" }, { name: "applicationDate", label: "Application date", type: "date" }, { name: "profession", label: "Visa profession" }, { name: "status", label: "Approval status", type: "select", options: ["Pending", "Submitted", "Approved", "Rejected"] }, attachment, remarks],
  Application: [file, { name: "applicationNumber", label: "Application number" }, { name: "applicationDate", label: "Application date", type: "date" }, { name: "profession", label: "Profession" }, { name: "status", label: "Application status", type: "select", options: ["Pending", "Submitted", "Approved", "Rejected"] }, attachment, remarks],
  "Confirm File": [file, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }, { name: "confirmationDate", label: "Confirmation date", type: "date" }, { name: "status", label: "Status", type: "select", options: ["Pending", "Confirmed", "Rejected", "Cancelled"] }, remarks],
  "E-Visa Stamping": [file, { name: "visaNumber", label: "Visa number" }, { name: "visaType", label: "Visa type" }, { name: "profession", label: "Visa profession" }, { name: "applicationDate", label: "Application date", type: "date" }, { name: "submissionDate", label: "Submission date", type: "date" }, { name: "issueDate", label: "Issue date", type: "date" }, { name: "stampingDate", label: "Stamping date", type: "date" }, { name: "expiryDate", label: "Visa expiry", type: "date" }, { name: "status", label: "Visa status", type: "select", options: ["Pending", "Submitted", "Stamped", "Rejected", "Done"] }, attachment, remarks],
  "Visa Done": [file, { name: "visaNumber", label: "Visa number", required: true }, { name: "visaType", label: "Visa type" }, { name: "profession", label: "Visa profession" }, { name: "issueDate", label: "Issue date", type: "date", required: true }, { name: "expiryDate", label: "Expiry date", type: "date", required: true }, { name: "status", label: "Status", type: "select", options: ["Done", "Expired", "Cancelled"] }, attachment, remarks],
  Manpower: [file, { name: "reference", label: "Manpower reference" }, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }, { name: "quantity", label: "Quantity", type: "number" }, { name: "submittedAt", label: "Submission date", type: "date" }, { name: "approvedAt", label: "Approval date", type: "date" }, { name: "status", label: "Status", type: "select", options: ["Pending", "Submitted", "Approved", "Rejected", "Done"] }, { name: "loanNeeded", label: "Loan needed", type: "checkbox" }, { name: "bmetFinger", label: "BMET Finger complete", type: "checkbox" }, { name: "bmetTraining", label: "BMET Training complete", type: "checkbox" }, remarks],
  "Ready To Flight": [file, { name: "readyDate", label: "Ready date", type: "date" }, { name: "visaClear", label: "Visa verified", type: "checkbox" }, { name: "travelClearance", label: "Travel clearance", type: "checkbox" }, { name: "paymentClear", label: "Payment clear", type: "checkbox" }, { name: "manpowerClear", label: "Manpower approved", type: "checkbox" }, { name: "acClear", label: "AC complete", type: "checkbox" }, { name: "loanClear", label: "Loan clear", type: "checkbox" }, { name: "bmetFinger", label: "BMET Finger", type: "checkbox" }, { name: "bmetTraining", label: "BMET Training", type: "checkbox" }, { name: "status", label: "Readiness", type: "select", options: ["Pending", "Ready", "Blocked"] }, { name: "blockers", label: "Blockers", type: "textarea", wide: true }, remarks],
  Flight: [file, { name: "airline", label: "Airline", required: true }, { name: "pnr", label: "PNR" }, { name: "ticketNumber", label: "Ticket number" }, { name: "flightNumber", label: "Flight number", required: true }, { name: "departureAt", label: "Departure date & time", type: "datetime-local", required: true }, { name: "arrivalAt", label: "Arrival date & time", type: "datetime-local" }, { name: "departureAirport", label: "Departure airport", required: true }, { name: "arrivalAirport", label: "Arrival airport" }, { name: "destination", label: "Destination", required: true }, { name: "baggage", label: "Baggage" }, attachment, remarks],
  "Hold File": [file, { name: "reason", label: "Hold reason", required: true }, { name: "actionDate", label: "Hold date", type: "date" }, { name: "expectedRelease", label: "Expected release", type: "date" }, { name: "owner", label: "Owner" }, remarks, attachment],
  "E-Visa Hold": [file, { name: "reason", label: "Hold reason", required: true }, { name: "actionDate", label: "Hold date", type: "date" }, { name: "expectedRelease", label: "Expected resolution", type: "date" }, { name: "profession", label: "Profession" }, { name: "company", label: "Company" }, { name: "source", label: "Source" }, { name: "customerStatus", label: "Customer status" }, { name: "officeStatus", label: "Office status" }, { name: "owner", label: "Owner" }, remarks, attachment],
  "Return File": [file, { name: "reason", label: "Return reason", required: true }, { name: "returnType", label: "Return type" }, { name: "actionDate", label: "Return date", type: "date" }, { name: "returnedBy", label: "Returned by" }, { name: "receivedBy", label: "Received by" }, { name: "financialImpact", label: "Financial impact", type: "number" }, remarks, attachment],
};

export const stageTableHeadings: Record<string, string[]> = {
  "Passport Management": ["FILE / CANDIDATE", "PHONE", "PASSPORT", "ISSUE DATE", "EXPIRY", "OFFICER"],
  "Passport List": ["FILE / CANDIDATE", "PHONE", "PASSPORT", "ISSUE DATE", "EXPIRY", "OFFICER"],
  "Passport Entry": ["FILE / CANDIDATE", "PHONE", "PASSPORT", "ISSUE DATE", "EXPIRY", "OFFICER"],
  Medical: ["FILE / CANDIDATE", "MEDICAL CENTER", "PASSPORT", "MEDICAL DATE", "EXPIRY / DAYS LEFT", "OFFICER"],
  MOFA: ["FILE / CANDIDATE", "MOFA NUMBER", "PASSPORT", "SUBMIT DATE", "DONE DATE", "OFFICER"],
  Takamul: ["FILE / CANDIDATE", "REGISTRATION", "VISA PROFESSION", "EXAM DATE", "CERTIFICATE", "OFFICER"],
  "KSA Bio Finger": ["FILE / CANDIDATE", "APPOINTMENT", "PASSPORT", "PRESENT DATE", "COMPLETED", "OFFICER"],
  "Bio Finger": ["FILE / CANDIDATE", "APPOINTMENT", "PASSPORT", "PRESENT DATE", "COMPLETED", "OFFICER"],
  "Police Clearance": ["FILE / CANDIDATE", "APPLICATION NO.", "PASSPORT", "APPLICATION DATE", "EXPIRY", "OFFICER"],
  "First Payment": ["FILE / CANDIDATE", "AMOUNT", "METHOD", "CURRENCY", "INVOICE", "COLLECTOR"],
  "Second Payment": ["FILE / CANDIDATE", "AMOUNT", "METHOD", "CURRENCY", "INVOICE", "COLLECTOR"],
  "Pending 2nd Payment": ["FILE / CANDIDATE", "TOTAL DUE", "PAID", "BALANCE", "DUE DATE", "COLLECTOR"],
  "Pre Confirm File": ["FILE / CANDIDATE", "COMPANY", "PROFESSION", "SALARY", "CONFIRM DATE", "OFFICER"],
  "Approval Application": ["FILE / CANDIDATE", "APPLICATION NO.", "PROFESSION", "APPLICATION DATE", "COMPANY", "OFFICER"],
  Application: ["FILE / CANDIDATE", "APPLICATION NO.", "PROFESSION", "APPLICATION DATE", "COMPANY", "OFFICER"],
  "Confirm File": ["FILE / CANDIDATE", "COMPANY", "PROFESSION", "CONFIRM DATE", "DESTINATION", "OFFICER"],
  "E-Visa Stamping": ["FILE / CANDIDATE", "VISA NUMBER", "VISA TYPE", "ISSUE DATE", "EXPIRY", "OFFICER"],
  "Visa Done": ["FILE / CANDIDATE", "VISA NUMBER", "VISA TYPE", "ISSUE DATE", "EXPIRY", "OFFICER"],
  Manpower: ["FILE / CANDIDATE", "REFERENCE", "PROFESSION", "SUBMITTED", "APPROVED", "OFFICER"],
  "Ready To Flight": ["FILE / CANDIDATE", "VISA / PAYMENT", "MANPOWER", "BMET FINGER", "READY DATE", "BLOCKERS"],
  "Ready to Flight": ["FILE / CANDIDATE", "VISA / PAYMENT", "MANPOWER", "BMET FINGER", "READY DATE", "BLOCKERS"],
  Flight: ["FILE / CANDIDATE", "FLIGHT", "PNR / TICKET", "DEPARTURE", "DESTINATION", "AIRLINE"],
  "E-Visa Hold": ["FILE / CANDIDATE", "HOLD REASON", "PROFESSION", "HOLD DATE", "EXPECTED RELEASE", "OWNER"],
  "Hold File": ["FILE / CANDIDATE", "HOLD REASON", "PREVIOUS STAGE", "HOLD DATE", "EXPECTED RELEASE", "OWNER"],
  "Return File": ["FILE / CANDIDATE", "RETURN REASON", "PREVIOUS STAGE", "RETURN DATE", "FINANCIAL IMPACT", "OWNER"],

};

export type StageFilterField = {
  name: string;
  label: string;
  type?: "text" | "date" | "select";
  placeholder?: string;
  options?: string[];
};

const identityFilters: StageFilterField[] = [
  { name: "identity", label: "Passport / client / phone", placeholder: "Search candidate" },
  { name: "officer", label: "Responsible officer", placeholder: "Officer name" },
  { name: "entryFrom", label: "Entry date from", type: "date" },
  { name: "entryTo", label: "Entry date to", type: "date" },
];
const processStatus: StageFilterField = { name: "stageStatus", label: "Process status", type: "select", options: ["Pending", "In Process", "Submitted", "Approved", "Rejected", "Done", "Completed"] };
const expiryFilters: StageFilterField[] = [{ name: "expiryFrom", label: "Expiry from", type: "date" }, { name: "expiryTo", label: "Expiry to", type: "date" }];

export const stageFilterFields: Record<string, StageFilterField[]> = {
  "Passport Management": [...identityFilters, { name: "profession", label: "Profession / category" }, { name: "verification", label: "Passport verification", type: "select", options: ["Pending", "Verified", "Rejected", "Correction Required"] }, ...expiryFilters],
  "Passport Entry": [...identityFilters, { name: "profession", label: "Profession / category" }, { name: "verification", label: "Passport verification", type: "select", options: ["Pending", "Verified", "Rejected"] }, ...expiryFilters],
  "Passport List": [...identityFilters, { name: "profession", label: "Profession / category" }, { name: "verification", label: "Passport verification", type: "select", options: ["Pending", "Verified", "Rejected"] }, ...expiryFilters],
  Medical: [...identityFilters, { name: "medicalCenter", label: "Medical center" }, { name: "medicalDateFrom", label: "Medical date from", type: "date" }, { name: "medicalDateTo", label: "Medical date to", type: "date" }, { name: "medicalResult", label: "Medical report", type: "select", options: ["Pending for Medical", "Medical Present", "Waiting for Report", "Fit", "Unfit", "Recall", "Medical Done"] }, { name: "contactMedical", label: "Contact medical", type: "select", options: ["Yes", "No"] }, ...expiryFilters],
  MOFA: [...identityFilters, { name: "mofaNumber", label: "MOFA number" }, { name: "medicalFit", label: "Medical fit", type: "select", options: ["Fit", "Unfit", "Pending"] }, processStatus],
  Takamul: [...identityFilters, { name: "registrationNumber", label: "Registration / certificate" }, { name: "profession", label: "Visa / Takamul profession" }, { name: "examFrom", label: "Exam date from", type: "date" }, { name: "examTo", label: "Exam date to", type: "date" }, processStatus],
  "KSA Bio Finger": [...identityFilters, { name: "appointmentFrom", label: "Appointment from", type: "date" }, { name: "appointmentTo", label: "Appointment to", type: "date" }, processStatus],
  "Bio Finger": [...identityFilters, { name: "appointmentFrom", label: "Appointment from", type: "date" }, { name: "appointmentTo", label: "Appointment to", type: "date" }, processStatus],

  "Police Clearance": [...identityFilters, { name: "applicationNumber", label: "Application number" }, processStatus, ...expiryFilters],
  "First Payment": [...identityFilters, { name: "amountFrom", label: "Amount from" }, { name: "amountTo", label: "Amount to" }, { name: "paymentMethod", label: "Payment method", type: "select", options: ["Cash", "Bank Transfer", "Mobile Banking", "Card"] }, { name: "paymentStatus", label: "Payment status", type: "select", options: ["PENDING", "DUE", "PARTIAL", "PAID", "FAILED", "REFUNDED"] }],
  "Second Payment": [...identityFilters, { name: "amountFrom", label: "Amount from" }, { name: "amountTo", label: "Amount to" }, { name: "paymentStatus", label: "Payment status", type: "select", options: ["PENDING", "DUE", "PARTIAL", "PAID", "OVERDUE"] }],
  "Pending 2nd Payment": [...identityFilters, { name: "dueFrom", label: "Due date from", type: "date" }, { name: "dueTo", label: "Due date to", type: "date" }, { name: "amountFrom", label: "Balance from" }, { name: "amountTo", label: "Balance to" }],
  "Pre Confirm File": [...identityFilters, { name: "company", label: "Company / demand" }, { name: "profession", label: "Profession" }, processStatus],
  "Approval Application": [...identityFilters, { name: "applicationNumber", label: "Application number" }, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }, processStatus],
  Application: [...identityFilters, { name: "applicationNumber", label: "Application number" }, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }, processStatus],
  "Confirm File": [...identityFilters, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }, processStatus],
  "E-Visa Stamping": [...identityFilters, { name: "visaNumber", label: "Visa number" }, { name: "profession", label: "Visa profession" }, processStatus, ...expiryFilters],
  "Visa Done": [...identityFilters, { name: "visaNumber", label: "Visa number" }, { name: "profession", label: "Visa profession" }, ...expiryFilters],
  Manpower: [...identityFilters, { name: "reference", label: "Manpower reference" }, { name: "profession", label: "Profession" }, processStatus],
  "Ready To Flight": [...identityFilters, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }, { name: "readiness", label: "Readiness", type: "select", options: ["Pending", "Ready", "Blocked"] }],
  "Ready to Flight": [...identityFilters, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }, { name: "readiness", label: "Readiness", type: "select", options: ["Pending", "Ready", "Blocked"] }],

  Flight: [...identityFilters, { name: "flightNumber", label: "Flight / PNR / ticket" }, { name: "departureFrom", label: "Departure from", type: "date" }, { name: "departureTo", label: "Departure to", type: "date" }, { name: "airline", label: "Airline" }],
  "E-Visa Hold": [...identityFilters, { name: "reason", label: "Hold reason" }, { name: "company", label: "Company" }, { name: "profession", label: "Profession" }],
  "Hold File": [...identityFilters, { name: "reason", label: "Hold reason" }, { name: "actionFrom", label: "Hold date from", type: "date" }, { name: "actionTo", label: "Hold date to", type: "date" }],
  "Return File": [...identityFilters, { name: "reason", label: "Return reason" }, { name: "actionFrom", label: "Return date from", type: "date" }, { name: "actionTo", label: "Return date to", type: "date" }],
};
