import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";

type Metadata = { medicalFitState?: string; medicalSlipState?: string; isReMedical?: boolean; remarks?: string; pictureCollected?: boolean; medicalSlip?: boolean; medicalSlipOffice?: string; visaProfession?: string };
type UploadRow = { fileNo?: string; candidateNo?: string; passportNumber?: string; status?: string; medicalFitState?: string; submitDate?: string; mofaNumber?: string; doneDate?: string; medicalSlipState?: string; isReMofa?: boolean; isReMedical?: boolean; remarks?: string };
const meta = (value: unknown): Metadata => value && typeof value === "object" ? value as Metadata : {};
const start = (value: string) => value ? new Date(`${value}T00:00:00`) : null; const end = (value: string) => value ? new Date(`${value}T23:59:59.999`) : null;
const within = (value: string | null, from: string, to: string) => (!from || Boolean(value && new Date(value) >= start(from)!)) && (!to || Boolean(value && new Date(value) <= end(to)!));
const boolMatch = (filter: string, value: boolean) => !filter || value === (filter === "Yes");

export async function GET(request: Request) {
  try {
    const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, "ksa", "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403);
    const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim(); const page = Math.max(1, Number(p("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(p("pageSize")) || 20));
    const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: { contains: "Saudi" }, mofa: { some: {} } }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, medical: { take: 1, orderBy: { createdAt: "desc" } }, mofa: { take: 1, orderBy: { createdAt: "desc" } } } });
    const rows = files.flatMap((file) => { const mofa = file.mofa[0]; if (!mofa) return []; const mm = meta(mofa.metadata); const medical = file.medical[0]; const md = meta(medical?.metadata); const expiry = medical?.expiryDate ?? null; const dob = file.candidate.dob; const daysLeft = expiry ? Math.ceil((expiry.getTime() - Date.now()) / 86_400_000) : null;
      return [{ id: file.id, mofaId: mofa.id, fileNo: file.fileNo, candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", officerId: file.assignedTo?.id ?? "", officerName: file.assignedTo?.name ?? "Unassigned", officeId: file.office?.id ?? "", office: file.office?.name ?? "SELF", company: file.company ?? "N/A", profession: file.profession ?? file.candidate.profession ?? "Uncategorized", visaProfession: mm.visaProfession ?? "N/A", age: dob ? Math.floor((Date.now() - dob.getTime()) / 31_557_600_000) : null, status: mofa.status, medicalFitState: mm.medicalFitState ?? medical?.result ?? "Pending", medicalFitDate: medical?.reportDate?.toISOString() ?? medical?.testDate?.toISOString() ?? null, medicalExpiry: expiry?.toISOString() ?? null, daysLeft, submitDate: mofa.submitDate?.toISOString() ?? null, mofaNumber: mofa.mofaNumber ?? "N/A", doneDate: mofa.doneDate?.toISOString() ?? null, isReMofa: mofa.isReMofa, isReMedical: Boolean(mm.isReMedical || medical?.isReMedical), medicalSlip: Boolean(md.medicalSlip), medicalSlipState: mm.medicalSlipState ?? "N/A", pictureCollected: Boolean(md.pictureCollected || mm.pictureCollected), medicalSlipOffice: mm.medicalSlipOffice ?? file.office?.name ?? "SELF", remarks: mm.remarks ?? "N/A" }];
    });
    const passport = p("passport").toLowerCase(), name = p("name").toLowerCase(), phone = p("phone").toLowerCase();
    const filtered = rows.filter((r) => (!passport || r.passportNumber.toLowerCase().includes(passport)) && (!name || r.name.toLowerCase().includes(name)) && (!phone || r.phone.toLowerCase().includes(phone)) && (!p("officer") || r.officerId === p("officer")) && (!p("office") || r.officeId === p("office")) && (!p("status") || r.status === p("status")) && (!p("medicalFit") || r.medicalFitState === p("medicalFit")) && within(r.medicalFitDate, p("medicalFrom"), p("medicalTo")) && within(r.submitDate, p("submitFrom"), p("submitTo")) && within(r.doneDate, p("doneFrom"), p("doneTo")) && (!p("withMedicalSlip") || r.medicalSlip === (p("withMedicalSlip") === "With")) && boolMatch(p("medicalSlip"), r.medicalSlip) && (!p("medicalSlipState") || r.medicalSlipState === p("medicalSlipState")) && boolMatch(p("pictureCollected"), r.pictureCollected) && boolMatch(p("reMofa"), r.isReMofa) && boolMatch(p("reMedical"), r.isReMedical));
    const [users, offices] = await Promise.all([prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.office.findMany({ where: { status: "ACTIVE", ...(session.user.officeId ? { id: session.user.officeId } : {}) }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const offset = (page - 1) * pageSize;
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, offices, statuses: [...new Set(rows.map((r) => r.status))].sort(), fitStatuses: [...new Set(rows.map((r) => r.medicalFitState))].sort(), slipStatuses: [...new Set(rows.map((r) => r.medicalSlipState))].sort() }, meta: { page, pageSize, total: filtered.length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}

export async function POST(request: Request) {
  try {
    const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, "ksa", "Create"))) throw new AppError("FORBIDDEN", "Create permission is required.", 403);
    const body = await request.json() as { rows?: UploadRow[] }; const rows = body.rows ?? []; if (!rows.length || rows.length > 500) throw new AppError("INVALID_CSV", "CSV must contain between 1 and 500 rows.", 422); let imported = 0; const errors: string[] = [];
    for (const [index, row] of rows.entries()) { const identifier = row.fileNo || row.candidateNo || row.passportNumber; if (!identifier) { errors.push(`Row ${index + 2}: fileNo, candidateNo or passportNumber is required.`); continue; } const file = await prisma.processingFile.findFirst({ where: { ...officeScope(session), country: { contains: "Saudi" }, OR: [{ fileNo: identifier }, { candidate: { candidateNo: identifier } }, { passport: { passportNumber: identifier } }] } }); if (!file) { errors.push(`Row ${index + 2}: no Saudi file found for ${identifier}.`); continue; }
      await prisma.mofaProcess.create({ data: { fileId: file.id, status: row.status || "Pending", mofaNumber: row.mofaNumber || null, submitDate: row.submitDate ? new Date(row.submitDate) : null, doneDate: row.doneDate ? new Date(row.doneDate) : null, isReMofa: Boolean(row.isReMofa), metadata: { medicalFitState: row.medicalFitState || "Pending", medicalSlipState: row.medicalSlipState || "Pending", isReMedical: Boolean(row.isReMedical), remarks: row.remarks || "" } } }); imported++;
    }
    return Response.json({ data: { imported, errors } }, { status: imported ? 201 : 422 });
  } catch (error) { return errorResponse(error); }
}
