CREATE TABLE `PassportProcess` (
  `id` VARCHAR(191) NOT NULL,
  `fileId` VARCHAR(191) NOT NULL,
  `passportNumber` VARCHAR(191) NOT NULL,
  `passportType` VARCHAR(191) NOT NULL DEFAULT 'Ordinary',
  `issueDate` DATETIME(3) NOT NULL,
  `issuePlace` VARCHAR(191) NULL,
  `issuingAuthority` VARCHAR(191) NULL,
  `expiryDate` DATETIME(3) NOT NULL,
  `nationality` VARCHAR(191) NULL,
  `verificationStatus` VARCHAR(191) NOT NULL DEFAULT 'Pending',
  `remarks` VARCHAR(191) NULL,
  `documentId` VARCHAR(191) NULL,
  `enteredBy` VARCHAR(191) NULL,
  `verifiedBy` VARCHAR(191) NULL,
  `verifiedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `PassportProcess_fileId_key`(`fileId`),
  UNIQUE INDEX `PassportProcess_passportNumber_key`(`passportNumber`),
  INDEX `PassportProcess_expiryDate_verificationStatus_idx`(`expiryDate`, `verificationStatus`),
  PRIMARY KEY (`id`),
  CONSTRAINT `PassportProcess_fileId_fkey` FOREIGN KEY (`fileId`) REFERENCES `ProcessingFile`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
