import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";

const start = (value: string) => value ? new Date(`${value}T00:00:00`) : null; const end = (value: string) => value ? new Date(`${value}T23:59:59.999`) : null;
const within = (value: string | null, from: string, to: string) => (!from || Boolean(value && new Date(value) >= start(from)!)) && (!to || Boolean(value && new Date(value) <= end(to)!));

export async function GET(request: Request) {
  try {
    const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, "ksa", "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403);
    const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim(); const page = Math.max(1, Number(p("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(p("pageSize")) || 20));
    const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: { contains: "Saudi" }, takamul: { some: {} } }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, takamul: { take: 1, orderBy: { createdAt: "desc" } } } });
    const rows = files.flatMap((file) => { const t = file.takamul[0]; if (!t) return []; const legacyReport = /waiting for result|passed|failed|certificate issued/i.test(t.status); const status = legacyReport ? (t.examDate ? "Present" : "Pending") : t.status; const reportStatus = t.reportStatus || (legacyReport ? t.status : /present/i.test(t.status) ? "Waiting for Result" : "Pending"); return [{ id: file.id, takamulId: t.id, fileNo: file.fileNo, candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", officerId: file.assignedTo?.id ?? "", officerName: file.assignedTo?.name ?? "Unassigned", officeId: file.office?.id ?? "", office: file.office?.name ?? "SELF", company: file.company ?? "N/A", status, reportStatus, examDate: t.examDate?.toISOString() ?? null, presentDate: t.presentDate?.toISOString() ?? null, centerDistrict: t.centerDistrict ?? "N/A", doneBy: t.doneBy ?? "N/A", visaProfession: t.visaProfession ?? "N/A", takamulProfession: t.takamulProfession ?? file.profession ?? file.candidate.profession ?? "N/A", registrationNumber: t.registrationNumber ?? "N/A", certificateNumber: t.certificateNumber ?? "N/A", remarks: t.remarks ?? "N/A" }]; });
    const passport = p("passport").toLowerCase(), name = p("name").toLowerCase(), phone = p("phone").toLowerCase(); const filtered = rows.filter((r) => (!passport || r.passportNumber.toLowerCase().includes(passport)) && (!name || r.name.toLowerCase().includes(name)) && (!phone || r.phone.toLowerCase().includes(phone)) && (!p("officer") || r.officerId === p("officer")) && (!p("office") || r.officeId === p("office")) && (!p("status") || r.status === p("status")) && (!p("reportStatus") || r.reportStatus === p("reportStatus")) && within(r.examDate, p("examFrom"), p("examTo")) && within(r.presentDate, p("presentFrom"), p("presentTo")) && (!p("centerDistrict") || r.centerDistrict === p("centerDistrict")) && (!p("doneBy") || r.doneBy === p("doneBy")) && (!p("visaProfession") || r.visaProfession === p("visaProfession")) && (!p("takamulProfession") || r.takamulProfession === p("takamulProfession")));
    const [users, offices] = await Promise.all([prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.office.findMany({ where: { status: "ACTIVE", ...(session.user.officeId ? { id: session.user.officeId } : {}) }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const offset = (page - 1) * pageSize; const values = (key: keyof typeof rows[number]) => [...new Set(rows.map((r) => String(r[key] ?? "")).filter((x) => x && x !== "N/A"))].sort();
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, offices, statuses: values("status"), reportStatuses: values("reportStatus"), districts: values("centerDistrict"), doneBy: values("doneBy"), visaProfessions: values("visaProfession"), takamulProfessions: values("takamulProfession") }, meta: { page, pageSize, total: filtered.length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}
