import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";
import { workflowCountryWhere, workflowModule } from "@/lib/workflow-country";

type Readiness = { readyDate?: string; visaClear?: boolean; travelClearance?: boolean; paymentClear?: boolean; manpowerClear?: boolean; acClear?: boolean; loanClear?: boolean; bmetFinger?: boolean; bmetTraining?: boolean; status?: string; blockers?: string; remarks?: string; groupName?: string };
type Requirements = { loanNeeded?: boolean; bmetFinger?: boolean; bmetTraining?: boolean };
const object = <T,>(value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as T : {} as T;
const start = (value: string) => value ? new Date(`${value}T00:00:00`) : null; const end = (value: string) => value ? new Date(`${value}T23:59:59.999`) : null;
const within = (value: string | null, from: string, to: string) => (!from || Boolean(value && new Date(value) >= start(from)!)) && (!to || Boolean(value && new Date(value) <= end(to)!)); const bool = (filter: string, value: boolean) => !filter || value === (filter === "Yes");

export async function GET(request: Request) {
  try {
const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, workflowModule(request), "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403); const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim(); const page = Math.max(1, Number(p("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(p("pageSize")) || 20));
const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: workflowCountryWhere(request), OR: [{ currentStage: "Ready To Flight" }, { workflowEvents: { some: { stage: "Ready To Flight" } } }] }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, workflowEvents: { where: { stage: "Ready To Flight" }, take: 1, orderBy: { createdAt: "desc" } }, manpower: { take: 1, orderBy: { createdAt: "desc" } }, visas: { take: 1, orderBy: { createdAt: "desc" } }, payments: { where: { type: "Second Payment" }, take: 1, orderBy: { createdAt: "desc" } }, flights: { take: 1, orderBy: { flight: { departureAt: "desc" } }, include: { flight: true } }, holds: { where: { type: "RETURN" }, orderBy: { createdAt: "desc" } } } });
    const rows = files.map((file) => { const event = file.workflowEvents[0], data = object<Readiness>(event?.data), manpower = file.manpower[0], requirements = object<Requirements>(manpower?.requirements), visa = file.visas[0], payment = file.payments[0], passenger = file.flights[0], flight = passenger?.flight; const paymentStatus = String(payment?.status ?? (data.paymentClear ? "PAID" : "PENDING")), manpowerStatus = manpower?.status ?? (data.manpowerClear ? "Approved" : "Pending"), bmetFinger = Boolean(data.bmetFinger ?? requirements.bmetFinger), bmetTraining = Boolean(data.bmetTraining ?? requirements.bmetTraining), acDone = Boolean(data.acClear), loanNeeded = Boolean(requirements.loanNeeded), ready = Boolean((data.status === "Ready" || event?.status === "Ready") || (paymentStatus === "PAID" && /approved|done/i.test(manpowerStatus) && bmetFinger && bmetTraining && visa)); return { id: file.id, eventId: event?.id ?? file.id, fileNo: file.fileNo, candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", officerId: file.assignedTo?.id ?? "", officer: file.assignedTo?.name ?? "Unassigned", officeId: file.office?.id ?? "", office: file.office?.name ?? "SELF", source: file.candidate.source ?? "N/A", company: file.company ?? "N/A", profession: file.profession ?? file.candidate.profession ?? "N/A", paymentStatus, manpowerStatus, acDone, loanNeeded, loanClear: Boolean(data.loanClear), bmetFinger, bmetTraining, readiness: data.status ?? event?.status ?? (ready ? "Ready" : "Pending"), readyDate: data.readyDate ?? event?.completedAt?.toISOString() ?? null, blockers: data.blockers ?? "N/A", remarks: data.remarks ?? "N/A", visaStatus: visa?.status ?? "Pending", visaExpiry: visa?.expiryDate?.toISOString() ?? null, flightStatus: passenger?.flown ? "Flown" : flight?.status ?? "Not Scheduled", flightDate: flight?.departureAt?.toISOString() ?? null, airline: flight?.airline ?? "N/A", flightName: flight?.flightNo ?? "N/A", location: flight ? `${flight.departureAirport} → ${flight.destination}` : "N/A", groupName: data.groupName ?? flight?.pnr ?? "N/A", returnedAfterFlight: file.holds.some((hold) => /flight/i.test(hold.previousStage)) }; });
    const filtered = rows.filter((r) => (!p("passport") || r.passportNumber.toLowerCase().includes(p("passport").toLowerCase())) && (!p("name") || r.name.toLowerCase().includes(p("name").toLowerCase())) && (!p("phone") || r.phone.toLowerCase().includes(p("phone").toLowerCase())) && (!p("officer") || r.officerId === p("officer")) && (!p("office") || r.officeId === p("office")) && (!p("paymentStatus") || r.paymentStatus === p("paymentStatus")) && (!p("manpowerStatus") || r.manpowerStatus === p("manpowerStatus")) && bool(p("acDone"), r.acDone) && bool(p("loanNeeded"), r.loanNeeded) && (!p("flightStatus") || r.flightStatus === p("flightStatus")) && bool(p("bmetFinger"), r.bmetFinger) && bool(p("bmetTraining"), r.bmetTraining) && within(r.flightDate, p("flightFrom"), p("flightTo")) && within(r.visaExpiry, p("visaFrom"), p("visaTo")) && (!p("airline") || r.airline.toLowerCase().includes(p("airline").toLowerCase())) && (!p("flightName") || r.flightName.toLowerCase().includes(p("flightName").toLowerCase())) && (!p("location") || r.location.toLowerCase().includes(p("location").toLowerCase())) && (!p("groupName") || r.groupName.toLowerCase().includes(p("groupName").toLowerCase())));
    const [users, offices] = await Promise.all([prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.office.findMany({ where: { status: "ACTIVE", ...(session.user.officeId ? { id: session.user.officeId } : {}) }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const values = (key: "paymentStatus" | "manpowerStatus" | "flightStatus") => [...new Set(rows.map((r) => r[key]).filter(Boolean))].sort(); const offset = (page - 1) * pageSize;
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, offices, paymentStatuses: values("paymentStatus"), manpowerStatuses: values("manpowerStatus"), flightStatuses: values("flightStatus") }, meta: { page, pageSize, total: filtered.length, returnedAfterFlight: rows.filter((r) => r.returnedAfterFlight).length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}
