import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";
import { workflowCountryWhere, workflowModule } from "@/lib/workflow-country";

const start = (value: string) => value ? new Date(`${value}T00:00:00`) : null;
const end = (value: string) => value ? new Date(`${value}T23:59:59.999`) : null;

export async function GET(request: Request) {
  try {
const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, workflowModule(request), "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403); const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim(); const page = Math.max(1, Number(p("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(p("pageSize")) || 20));
const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: workflowCountryWhere(request), OR: [{ currentStage: { in: ["Pending 2nd Payment", "Pending Second Payment"] } }, { payments: { some: { type: "Second Payment" } } }] }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, payments: { where: { type: "Second Payment" }, take: 1, orderBy: { createdAt: "desc" } }, visas: { take: 1, orderBy: { createdAt: "desc" } } } });
    const rows = files.map((file) => { const payment = file.payments[0], visa = file.visas[0]; const amount = Number(payment?.amount ?? 0), paymentStatus = String(payment?.status ?? "PENDING"), visaStatus = visa?.status ?? "Pending"; return { id: file.id, paymentId: payment?.id ?? file.id, fileNo: file.fileNo, candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", officerId: file.assignedTo?.id ?? "", officer: file.assignedTo?.name ?? "Unassigned", office: file.office?.name ?? "SELF", company: file.company ?? "N/A", profession: file.profession ?? file.candidate.profession ?? "N/A", visaStatus, visaNumber: visa?.visaNumber ?? "N/A", visaExpiry: visa?.expiryDate?.toISOString() ?? null, visaDone: /done|stamped/i.test(visaStatus), paymentStatus, amount, paidAmount: paymentStatus === "PAID" ? amount : 0, balance: paymentStatus === "PAID" ? 0 : amount, currency: payment?.currency ?? "BDT", dueDate: payment?.dueDate?.toISOString() ?? null, collectedAt: payment?.collectedAt?.toISOString() ?? null, collector: payment?.collector ?? "N/A" }; });
    const expiryFrom = start(p("expiryFrom")), expiryTo = end(p("expiryTo")); const amountFrom = Number(p("amountFrom")) || 0, amountTo = Number(p("amountTo")) || Infinity; const filtered = rows.filter((r) => (!p("passport") || r.passportNumber.toLowerCase().includes(p("passport").toLowerCase())) && (!p("name") || r.name.toLowerCase().includes(p("name").toLowerCase())) && (!p("phone") || r.phone.toLowerCase().includes(p("phone").toLowerCase())) && (!p("officer") || r.officerId === p("officer")) && (!p("visaStatus") || r.visaStatus === p("visaStatus")) && (!p("paymentStatus") || r.paymentStatus === p("paymentStatus")) && (!p("completion") || (p("completion") === "Both Done" ? r.visaDone && r.paymentStatus === "PAID" : p("completion") === "Visa Done" ? r.visaDone : p("completion") === "Second Payment Done" ? r.paymentStatus === "PAID" : !r.visaDone || r.paymentStatus !== "PAID")) && (!expiryFrom || Boolean(r.visaExpiry && new Date(r.visaExpiry) >= expiryFrom)) && (!expiryTo || Boolean(r.visaExpiry && new Date(r.visaExpiry) <= expiryTo)) && r.paidAmount >= amountFrom && r.paidAmount <= amountTo && (!p("excludeExpired") || Boolean(r.visaExpiry && new Date(r.visaExpiry) >= new Date())));
    const users = await prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }); const values = (key: "visaStatus" | "paymentStatus") => [...new Set(rows.map((r) => r[key]).filter(Boolean))].sort(); const offset = (page - 1) * pageSize;
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, visaStatuses: values("visaStatus"), paymentStatuses: values("paymentStatus") }, meta: { page, pageSize, total: filtered.length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}
