import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";
import { workflowCountryWhere, workflowModule } from "@/lib/workflow-country";

type Meta = { medicalFitState?: string; isReMedical?: boolean };
const meta = (value: unknown): Meta => value && typeof value === "object" ? value as Meta : {};
const start = (value: string) => value ? new Date(`${value}T00:00:00`) : null; const end = (value: string) => value ? new Date(`${value}T23:59:59.999`) : null;
const boolMatch = (filter: string, value: boolean) => !filter || value === (filter === "Yes");

export async function GET(request: Request) {
  try {
const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, workflowModule(request), "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403); const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim(); const page = Math.max(1, Number(p("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(p("pageSize")) || 20));
const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: workflowCountryWhere(request), payments: { some: { type: "First Payment" } } }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, payments: { where: { type: "First Payment" }, take: 1, orderBy: { createdAt: "desc" } }, medical: { take: 1, orderBy: { createdAt: "desc" } }, mofa: { take: 1, orderBy: { createdAt: "desc" } }, takamul: { take: 1, orderBy: { createdAt: "desc" } }, biometrics: { where: { type: "KSA Bio Finger" }, take: 1, orderBy: { createdAt: "desc" } }, police: { take: 1, orderBy: { createdAt: "desc" } } } });
    const rows = files.flatMap((file) => { const payment = file.payments[0]; if (!payment) return []; const medical = file.medical[0]; const mofa = file.mofa[0]; const medicalMeta = meta(medical?.metadata), mofaMeta = meta(mofa?.metadata); const medicalFit = /fit|done/i.test(medical?.result ?? "") && !/unfit/i.test(medical?.result ?? ""); const amount = Number(payment.amount); return [{ id: file.id, paymentId: payment.id, paymentNo: payment.paymentNo, invoiceNo: payment.invoiceNo ?? "N/A", candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", officerId: file.assignedTo?.id ?? "", officerName: file.assignedTo?.name ?? "Unassigned", officeId: file.office?.id ?? "", office: file.office?.name ?? "SELF", company: file.company ?? "N/A", profession: file.profession ?? file.candidate.profession ?? "N/A", amount, currency: payment.currency, method: payment.method ?? "N/A", status: payment.status, collectedAt: payment.collectedAt?.toISOString() ?? null, collector: payment.collector ?? "N/A", medicalFit, medicalStatus: medical?.result ?? "Pending", medicalExpiry: medical?.expiryDate?.toISOString() ?? null, reMedical: Boolean(medical?.isReMedical || medicalMeta.isReMedical || mofaMeta.isReMedical), reMofa: Boolean(mofa?.isReMofa), takamulResult: file.takamul[0]?.reportStatus || file.takamul[0]?.status || "Pending", bioStatus: file.biometrics[0]?.status ?? "Pending", mofaStatus: mofa?.status ?? "Pending", policeStatus: file.police[0]?.status ?? "Pending" }]; });
    const passport = p("passport").toLowerCase(), name = p("name").toLowerCase(), phone = p("phone").toLowerCase(); const fromAmount = Number(p("amountFrom")) || 0, toAmount = Number(p("amountTo")) || Infinity; const expiryFrom = start(p("expiryFrom")), expiryTo = end(p("expiryTo")); const filtered = rows.filter((r) => (!passport || r.passportNumber.toLowerCase().includes(passport)) && (!name || r.name.toLowerCase().includes(name)) && (!phone || r.phone.toLowerCase().includes(phone)) && (!p("officer") || r.officerId === p("officer")) && (!p("office") || r.officeId === p("office")) && (!p("eligibility") || (p("eligibility") === "Both" ? r.medicalFit && r.amount > 0 : p("eligibility") === "Medical" ? r.medicalFit : r.amount > 0)) && (!p("amountBucket") || (p("amountBucket") === "50000" ? r.amount === 50000 : p("amountBucket") === "Below" ? r.amount < 50000 : r.amount > 50000)) && (!p("takamulResult") || r.takamulResult === p("takamulResult")) && (!p("bioStatus") || r.bioStatus === p("bioStatus")) && (!p("mofaStatus") || r.mofaStatus === p("mofaStatus")) && (!p("policeStatus") || r.policeStatus === p("policeStatus")) && (!expiryFrom || Boolean(r.medicalExpiry && new Date(r.medicalExpiry) >= expiryFrom)) && (!expiryTo || Boolean(r.medicalExpiry && new Date(r.medicalExpiry) <= expiryTo)) && r.amount >= fromAmount && r.amount <= toAmount && boolMatch(p("reMedical"), r.reMedical) && boolMatch(p("reMofa"), r.reMofa) && (!p("excludeExpired") || Boolean(r.medicalExpiry && new Date(r.medicalExpiry) >= new Date())));
    const [users, offices] = await Promise.all([prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.office.findMany({ where: { status: "ACTIVE", ...(session.user.officeId ? { id: session.user.officeId } : {}) }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const values = (key: keyof typeof rows[number]) => [...new Set(rows.map((r) => String(r[key] ?? "")).filter(Boolean))].sort(); const offset = (page - 1) * pageSize;
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, offices, takamulResults: values("takamulResult"), bioStatuses: values("bioStatus"), mofaStatuses: values("mofaStatus"), policeStatuses: values("policeStatus") }, meta: { page, pageSize, total: filtered.length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}
