import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";
import { workflowCountryWhere, workflowModule } from "@/lib/workflow-country";

type Readiness = { acClear?: boolean; loanClear?: boolean; bmetFinger?: boolean; bmetTraining?: boolean; groupName?: string };
type Requirements = { loanNeeded?: boolean; bmetFinger?: boolean; bmetTraining?: boolean };
const object = <T,>(value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as T : {} as T;
const start = (value: string) => value ? new Date(`${value}T00:00:00`) : null; const end = (value: string) => value ? new Date(`${value}T23:59:59.999`) : null; const within = (value: string | null, from: string, to: string) => (!from || Boolean(value && new Date(value) >= start(from)!)) && (!to || Boolean(value && new Date(value) <= end(to)!)); const bool = (filter: string, value: boolean) => !filter || value === (filter === "Yes");

export async function GET(request: Request) {
  try {
const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, workflowModule(request), "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403); const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim(); const page = Math.max(1, Number(p("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(p("pageSize")) || 20));
const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: workflowCountryWhere(request), OR: [{ currentStage: "Flight" }, { flights: { some: {} } }] }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, workflowEvents: { where: { stage: "Ready To Flight" }, take: 1, orderBy: { createdAt: "desc" } }, manpower: { take: 1, orderBy: { createdAt: "desc" } }, visas: { take: 1, orderBy: { createdAt: "desc" } }, payments: { where: { type: "Second Payment" }, take: 1, orderBy: { createdAt: "desc" } }, flights: { take: 1, orderBy: { flight: { departureAt: "desc" } }, include: { flight: true } } } });
    const rows = files.map((file) => { const readiness = object<Readiness>(file.workflowEvents[0]?.data), manpower = file.manpower[0], requirements = object<Requirements>(manpower?.requirements), visa = file.visas[0], payment = file.payments[0], passenger = file.flights[0], flight = passenger?.flight; return { id: file.id, flightId: flight?.id ?? file.id, fileNo: file.fileNo, candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", officerId: file.assignedTo?.id ?? "", officer: file.assignedTo?.name ?? "Unassigned", officeId: file.office?.id ?? "", office: file.office?.name ?? "SELF", agent: file.agent ?? "N/A", company: file.company ?? "N/A", profession: file.profession ?? file.candidate.profession ?? "N/A", paymentStatus: String(payment?.status ?? "PENDING"), manpowerStatus: manpower?.status ?? "Pending", acDone: Boolean(readiness.acClear), loanNeeded: Boolean(requirements.loanNeeded), bmetFinger: Boolean(readiness.bmetFinger ?? requirements.bmetFinger), bmetTraining: Boolean(readiness.bmetTraining ?? requirements.bmetTraining), visaStatus: visa?.status ?? "Pending", visaExpiry: visa?.expiryDate?.toISOString() ?? null, flightStatus: passenger?.flown ? "Flown" : flight?.status ?? "Not Scheduled", flightDate: flight?.departureAt?.toISOString() ?? null, arrivalDate: flight?.arrivalAt?.toISOString() ?? null, airline: flight?.airline ?? "N/A", flightName: flight?.flightNo ?? "N/A", pnr: flight?.pnr ?? "N/A", location: flight ? `${flight.departureAirport} → ${flight.destination}` : "N/A", groupName: readiness.groupName ?? flight?.pnr ?? "N/A", ticketNo: passenger?.ticketNo ?? "N/A", baggage: passenger?.baggage ?? "N/A" }; });
    const filtered = rows.filter((r) => (!p("passport") || r.passportNumber.toLowerCase().includes(p("passport").toLowerCase())) && (!p("name") || r.name.toLowerCase().includes(p("name").toLowerCase())) && (!p("phone") || r.phone.toLowerCase().includes(p("phone").toLowerCase())) && (!p("officer") || r.officerId === p("officer")) && (!p("office") || r.officeId === p("office")) && (!p("flightStatus") || r.flightStatus === p("flightStatus")) && (!p("paymentStatus") || r.paymentStatus === p("paymentStatus")) && (!p("manpowerStatus") || r.manpowerStatus === p("manpowerStatus")) && bool(p("acDone"), r.acDone) && bool(p("loanNeeded"), r.loanNeeded) && (!p("agent") || r.agent === p("agent")) && bool(p("bmetFinger"), r.bmetFinger) && bool(p("bmetTraining"), r.bmetTraining) && within(r.flightDate, p("flightFrom"), p("flightTo")) && within(r.visaExpiry, p("visaFrom"), p("visaTo")) && (!p("airline") || r.airline.toLowerCase().includes(p("airline").toLowerCase())) && (!p("flightName") || r.flightName.toLowerCase().includes(p("flightName").toLowerCase())) && (!p("location") || r.location.toLowerCase().includes(p("location").toLowerCase())) && (!p("groupName") || r.groupName.toLowerCase().includes(p("groupName").toLowerCase())));
    const [users, offices] = await Promise.all([prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.office.findMany({ where: { status: "ACTIVE", ...(session.user.officeId ? { id: session.user.officeId } : {}) }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const values = (key: "flightStatus" | "paymentStatus" | "manpowerStatus" | "agent") => [...new Set(rows.map((r) => r[key]).filter((x) => x && x !== "N/A"))].sort(); const offset = (page - 1) * pageSize;
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, offices, flightStatuses: values("flightStatus"), paymentStatuses: values("paymentStatus"), manpowerStatuses: values("manpowerStatus"), agents: values("agent") }, meta: { page, pageSize, total: filtered.length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}
