"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; returnId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officer: string; office: string; profession: string; company: string; paidAmount: number; refunded: number; netAmount: number; due: number; returnAmount: number; holdBy: string; returnedBy: string; receivedBy: string; previousStatus: string; returnedAt: string; reason: string; remarks: string; attachment: string; status: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; previousStatuses: string[]; professions: string[]; companies: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", officer: "", returnedFrom: "", returnedTo: "", previousStatus: "", profession: "", company: "", paidFrom: "", paidTo: "" };
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));

export function KsaReturnedFilesPage({ country = "Saudi" }: { country?: string }) {
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const query = useQuery({ queryKey: ["ksa-returned-files", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/returned-files?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load returned files"); return response.json() as Promise<Data>; } }); const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const choices = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const download = () => { const q = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = [["SL", "Client", "Candidate", "Phone", "Passport", "Profession", "Company", "Paid Amount", "Refunded", "Net Amount", "Due", "Return Amount", "Officer", "Hold By", "Returned By", "Received By", "Previous Status", "Returned At", "Return Reason", "Remarks"].join(","), ...rows.map((row, index) => [index + 1, row.name, row.candidateNo, row.phone, row.passportNumber, row.profession, row.company, row.paidAmount, row.refunded, row.netAmount, row.due, row.returnAmount, row.officer, row.holdBy, row.returnedBy, row.receivedBy, row.previousStatus, dateLabel(row.returnedAt), row.reason, row.remarks].map(q).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "returned-files.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="ksa-returned-page"><header><div className="breadcrumb">Dashboard / Returned File</div><h1>Returned File</h1></header><section className="returned-card"><div className="returned-filters"><Field label="Passport No"><input className="accent" placeholder="Passport number..." value={filters.passport} onChange={(e) => set("passport", e.target.value)} /></Field><Field label="Officer"><Select placeholder="Select Officer" value={filters.officer} options={(choices?.users ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("officer", v)} /></Field><Field label="Date range (Returned at)"><div className="returned-range"><input aria-label="Returned from" type="date" value={filters.returnedFrom} onChange={(e) => set("returnedFrom", e.target.value)} /><input aria-label="Returned to" type="date" value={filters.returnedTo} onChange={(e) => set("returnedTo", e.target.value)} /></div></Field><Field label="Previous Status"><Select placeholder="Select an option" value={filters.previousStatus} options={(choices?.previousStatuses ?? []).map(asOption)} onChange={(v) => set("previousStatus", v)} /></Field><Field label="Profession"><Select placeholder="All professions" value={filters.profession} options={(choices?.professions ?? []).map(asOption)} onChange={(v) => set("profession", v)} /></Field><Field label="Company"><Select placeholder="All companies" value={filters.company} options={(choices?.companies ?? []).map(asOption)} onChange={(v) => set("company", v)} /></Field><Field label="Paid amount (from)"><input type="number" placeholder="Min amount" value={filters.paidFrom} onChange={(e) => set("paidFrom", e.target.value)} /></Field><Field label="Paid amount (to)"><input type="number" placeholder="Max amount" value={filters.paidTo} onChange={(e) => set("paidTo", e.target.value)} /></Field><div className="returned-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>
    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Returned files could not be loaded.</div>}<div className="returned-toolbar"><button onClick={download}><Download size={16} />Download CSV</button><div><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b> of <b>{meta.total}</b> Results</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select></div></div><div className="returned-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Client Info</th><th>Profession</th><th>Company</th><th>Paid Amount</th><th>Refunded</th><th>Net Amount</th><th>Due</th><th>Return Amount</th><th>Officer</th><th>Hold By</th><th>Returned By</th><th>Received By</th><th>Previous Status</th><th>Returned At</th><th>Return Reason</th><th>Remarks</th><th>Status</th><th>Attachment</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.returnId}><td>{(page - 1) * pageSize + index + 1}</td><td><Link href={`/file/${row.id}`}>Actions</Link></td><td className="client-info"><b>{row.name}</b><span>{row.phone}</span><Link href={`/file/${row.id}`}>{row.candidateNo}</Link><small>{row.passportNumber}</small></td><td>{row.profession}</td><td>{row.company}</td><td><Money value={row.paidAmount} good /><small>Net: {row.netAmount.toLocaleString()}</small></td><td><Money value={row.refunded} /></td><td><Money value={row.netAmount} good /></td><td><Money value={row.due} due /></td><td><Money value={row.returnAmount} /></td><td>{row.officer}</td><td>{row.holdBy}</td><td>{row.returnedBy}</td><td>{row.receivedBy}</td><td><span className={`previous-badge ${stageClass(row.previousStatus)}`}>{row.previousStatus}</span></td><td>{dateLabel(row.returnedAt)}</td><td>{row.reason}</td><td>{row.remarks}</td><td>{row.status}</td><td>{row.attachment}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={20}>No data available in table</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div>
  </section></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span>{label}</span>{children}</label>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <select value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>; }
function Money({ value, good = false, due = false }: { value: number; good?: boolean; due?: boolean }) { return <strong className={`return-money ${good ? "good" : ""} ${due ? "due" : ""}`}>{value.toLocaleString(undefined, { minimumFractionDigits: 2 })} ৳</strong>; }
function asOption(value: string) { return [value, value]; } function stageClass(value: string) { return /mofa/i.test(value) ? "mofa" : /medical/i.test(value) ? "medical" : "passport"; }
