"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, FileDown, Search, Upload } from "lucide-react";
import Link from "next/link";
import { useRef, useState } from "react";

type Row = { id: string; mofaId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officerName: string; officeId: string; office: string; company: string; profession: string; visaProfession: string; age: number | null; status: string; medicalFitState: string; medicalFitDate: string | null; medicalExpiry: string | null; daysLeft: number | null; submitDate: string | null; mofaNumber: string; doneDate: string | null; isReMofa: boolean; isReMedical: boolean; medicalSlip: boolean; medicalSlipState: string; pictureCollected: boolean; medicalSlipOffice: string; remarks: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }>; statuses: string[]; fitStatuses: string[]; slipStatuses: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", office: "", status: "", medicalFit: "", medicalFrom: "", medicalTo: "", submitFrom: "", submitTo: "", doneFrom: "", doneTo: "", withMedicalSlip: "", medicalSlip: "", medicalSlipState: "", pictureCollected: "", reMofa: "", reMedical: "" };
const yesNo = [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }]; const opt = (value: string) => ({ value, label: value });
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaMofaPage({ country = "Saudi" }: { country?: string }) {
  const countryLabel = country === "Saudi" ? "Saudi Arabia" : country;
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [message, setMessage] = useState(""); const inputRef = useRef<HTMLInputElement>(null); const client = useQueryClient();
  const query = useQuery({ queryKey: ["ksa-mofa", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/mofa?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load MOFA records"); return response.json() as Promise<Data>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const f = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const csv = (sample = false) => { const headers = ["fileNo", "candidateNo", "passportNumber", "status", "medicalFitState", "submitDate", "mofaNumber", "doneDate", "medicalSlipState", "isReMofa", "isReMedical", "remarks"]; const quote = (v: unknown) => `"${String(v ?? "").replaceAll('"', '""')}"`; const content = sample ? [headers.join(","), "FILE-001,,,Pending,Fit,2026-08-10,,,Pending,false,false,"] : [["SL", "File Type", "Status", "Customer", "Candidate No", "Phone", "Medical Fit", "Medical Fit Date", "Medical Expiry", "Days Left", "Submit Date", "MOFA Number", "Done Date", "Visa Profession", "Profession", "Officer", "Age", "Office", "Medical Slip Office", "Company", "Remarks"].join(","), ...rows.map((r, i) => [i + 1, fileTypes(r).join(" | "), r.status, r.name, r.candidateNo, r.phone, r.medicalFitState, dateLabel(r.medicalFitDate), dateLabel(r.medicalExpiry), r.daysLeft ?? "", dateLabel(r.submitDate), r.mofaNumber, dateLabel(r.doneDate), r.visaProfession, r.profession, r.officerName, r.age ?? "", r.office, r.medicalSlipOffice, r.company, r.remarks].map(quote).join(","))]; saveCsv(content.join("\n"), sample ? "mofa-upload-sample.csv" : `${country.toLowerCase()}-mofa-list.csv`); };
  const upload = async (file?: File) => { if (!file) return; setMessage("Uploading CSV..."); try { const parsed = parseCsv(await file.text()); const response = await fetch(`/api/ksa/mofa?country=${encodeURIComponent(country)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows: parsed }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "CSV upload failed"); setMessage(`${result.data.imported} MOFA record(s) imported${result.data.errors.length ? `; ${result.data.errors.length} row(s) skipped` : ""}.`); await client.invalidateQueries({ queryKey: ["ksa-mofa"] }); await client.invalidateQueries({ queryKey: ["ksa-queue-counts"] }); } catch (error) { setMessage(error instanceof Error ? error.message : "CSV upload failed"); } finally { if (inputRef.current) inputRef.current.value = ""; } };
  return <div className="ksa-mofa-page">
    <header><div className="breadcrumb">Dashboard / {countryLabel} Mofa</div><h1>{countryLabel} Mofa</h1></header>
    <section className="ksa-mofa-card">
      <div className="ksa-mofa-filters">

        <SearchField placeholder="Passport number..." value={filters.passport} onChange={(v) => set("passport", v)} accent /><SearchField placeholder="Client Name..." value={filters.name} onChange={(v) => set("name", v)} /><SearchField placeholder="Phone number..." value={filters.phone} onChange={(v) => set("phone", v)} />
        <Select placeholder="Select Officer" value={filters.officer} options={(f?.users ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(v) => set("officer", v)} /><Select placeholder="Select Office" value={filters.office} options={(f?.offices ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(v) => set("office", v)} /><Select placeholder="Select Mofa Status" value={filters.status} options={["Pending", "Submitted", "Approved", "Rejected", "Done", ...(f?.statuses ?? [])].filter(unique).map(opt)} onChange={(v) => set("status", v)} />
        <Select placeholder="Medical fit status" value={filters.medicalFit} options={["Fit", "Unfit", "Pending", ...(f?.fitStatuses ?? [])].filter(unique).map(opt)} onChange={(v) => set("medicalFit", v)} /><Range label="Medical fit date range" from={filters.medicalFrom} to={filters.medicalTo} onFrom={(v) => set("medicalFrom", v)} onTo={(v) => set("medicalTo", v)} /><Range label="MOFA submit date range" from={filters.submitFrom} to={filters.submitTo} onFrom={(v) => set("submitFrom", v)} onTo={(v) => set("submitTo", v)} /><Range label="MOFA done date range" from={filters.doneFrom} to={filters.doneTo} onFrom={(v) => set("doneFrom", v)} onTo={(v) => set("doneTo", v)} />
        <Select placeholder="With / Without Medical Slip" value={filters.withMedicalSlip} options={[{ value: "With", label: "With Medical Slip" }, { value: "Without", label: "Without Medical Slip" }]} onChange={(v) => set("withMedicalSlip", v)} /><Select placeholder="Select Medical Slip" value={filters.medicalSlip} options={yesNo} onChange={(v) => set("medicalSlip", v)} /><Select placeholder="Select Medical Slip Status" value={filters.medicalSlipState} options={["Pending", "Available", "Verified", ...(f?.slipStatuses ?? [])].filter(unique).map(opt)} onChange={(v) => set("medicalSlipState", v)} /><Select placeholder="Select Picture Collected" value={filters.pictureCollected} options={yesNo} onChange={(v) => set("pictureCollected", v)} />
        <div className="mofa-checks"><Check label="Re-MOFA Files" checked={filters.reMofa === "Yes"} onChange={(v) => set("reMofa", v ? "Yes" : "")} /><Check label="Re-Medical Files" checked={filters.reMedical === "Yes"} onChange={(v) => set("reMedical", v ? "Yes" : "")} /></div>
        <div className="mofa-filter-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div>
      </div>
      <div className="mofa-csv-actions"><button onClick={() => csv(true)}><FileDown size={17} />Download<br />Sample CSV</button><button onClick={() => inputRef.current?.click()}><Upload size={17} />Upload CSV</button><button onClick={() => csv()}><Download size={17} />Download<br />(CSV)</button><input ref={inputRef} hidden type="file" accept=".csv,text/csv" onChange={(e) => upload(e.target.files?.[0])} /></div>
      {message && <div className="mofa-message">{message}</div>}{query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">MOFA records could not be loaded.</div>}
      <div className="mofa-toolbar"><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b> to <b>{Math.min(page * pageSize, meta.total)}</b> of <b>{meta.total}</b> Results</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select></div>
      <div className="ksa-mofa-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>File Type</th><th>Status</th><th>Customer Information</th><th>Medical fit status</th><th>Medical fit date</th><th>Medical Expiry</th><th>Day Left</th><th>Submit Date</th><th>Mofa Number</th><th>Done Date</th><th>Visa Profession</th><th>Profession</th><th>Officer</th><th>Age</th><th>Office</th><th>Medical Slip Office</th><th>Company</th><th>Remarks</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r.mofaId}><td>{(page - 1) * pageSize + i + 1}</td><td><Link href={`/file/${r.id}`}>Actions</Link></td><td><div className="mofa-file-types">{fileTypes(r).map((x) => <span key={x}>{x}</span>)}</div></td><td><span className="mofa-status">{r.status}</span></td><td className="client-info"><b>{r.name}</b><Link href={`/file/${r.id}`}>{r.candidateNo}</Link><span>Phone: {r.phone}</span></td><td><span className="fit-badge">{r.medicalFitState}</span></td><td>{dateLabel(r.medicalFitDate)}</td><td>{dateLabel(r.medicalExpiry)}</td><td className={r.daysLeft !== null && r.daysLeft <= 30 ? "days-low" : "days-good"}>{r.daysLeft === null ? "N/A" : `${r.daysLeft} days left`}</td><td>{dateLabel(r.submitDate)}</td><td>{r.mofaNumber}</td><td>{dateLabel(r.doneDate)}</td><td>{r.visaProfession}</td><td>{r.profession}</td><td>{r.officerName}</td><td>{r.age ?? "N/A"}</td><td>{r.office}</td><td><span className="fit-badge">{r.medicalSlipOffice}</span></td><td>{r.company}</td><td>{r.remarks}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={20}>No MOFA records match these filters.</td></tr>}</tbody></table></div>
      <div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} />Previous</button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}>Next<ChevronRight size={16} /></button></div>
    </section>
  </div>;
}

function SearchField({ placeholder, value, onChange, accent = false }: { placeholder: string; value: string; onChange: (v: string) => void; accent?: boolean }) { return <div className={`mofa-search ${accent ? "accent" : ""}`}><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: Array<{ value: string; label: string }>; onChange: (v: string) => void }) { return <select aria-label={placeholder} value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select>; }
function Range({ label, from, to, onFrom, onTo }: { label: string; from: string; to: string; onFrom: (v: string) => void; onTo: (v: string) => void }) { return <label className="mofa-range"><span>{label}</span><div><input aria-label={`${label} from`} type="date" value={from} onChange={(e) => onFrom(e.target.value)} /><input aria-label={`${label} to`} type="date" value={to} onChange={(e) => onTo(e.target.value)} /></div></label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) { return <label><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} />{label}</label>; }
function fileTypes(r: Row) { return r.isReMedical || r.isReMofa ? [...(r.isReMedical ? ["RE-MEDICAL"] : []), ...(r.isReMofa ? ["RE-MOFA"] : [])] : ["NORMAL"]; }
function unique(value: string, index: number, array: string[]) { return array.indexOf(value) === index; }
function saveCsv(content: string, name: string) { const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function parseCsv(text: string) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error("CSV contains no data rows."); const parse = (line: string) => { const values: string[] = []; let value = "", quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"' && quoted && line[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { values.push(value.trim()); value = ""; } else value += char; } values.push(value.trim()); return values; }; const headers = parse(lines[0]); return lines.slice(1).map((line) => Object.fromEntries(headers.map((header, index) => { const raw = parse(line)[index] ?? ""; return [header, /^(true|false)$/i.test(raw) ? raw.toLowerCase() === "true" : raw]; }))); }
