"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; manpowerId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officer: string; agent: string; officeId: string; office: string; company: string; profession: string; reference: string; quantity: number; submittedAt: string | null; approvedAt: string | null; status: string; loanNeeded: boolean; bmetFinger: boolean; bmetTraining: boolean; readyToFlight: boolean; visaStatus: string; secondPayment: number; remarks: string; document: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }>; agents: string[]; statuses: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", agent: "", status: "", loanNeeded: "", office: "", readyToFlight: "", bmetFinger: "", bmetTraining: "", paymentBucket: "" };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaManpowerPage({ country = "Saudi", title = "Manpower", stage = "Manpower" }: { country?: string; title?: string; stage?: string }) {
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const query = useQuery({ queryKey: ["ksa-manpower", country, stage, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, stage, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/manpower?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error(`Could not load ${title} records`); return response.json() as Promise<Data>; } }); const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const choices = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const download = () => { const q = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = [["SL", "Client", "Candidate", "Phone", "Passport", "Reference", "Status", "Profession", "Company", "Agent", "Officer", "Office", "Loan", "BMET Finger", "BMET Training", "Ready To Flight", "Second Payment", "Submitted", "Approved"].join(","), ...rows.map((row, index) => [index + 1, row.name, row.candidateNo, row.phone, row.passportNumber, row.reference, row.status, row.profession, row.company, row.agent, row.officer, row.office, yes(row.loanNeeded), yes(row.bmetFinger), yes(row.bmetTraining), yes(row.readyToFlight), row.secondPayment, dateLabel(row.submittedAt), dateLabel(row.approvedAt)].map(q).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "ksa-manpower.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="ksa-manpower-page"><header><div className="breadcrumb">Dashboard / {title}</div><h1>{title}</h1></header><section className="manpower-card"><div className="manpower-filters"><SearchField placeholder="Passport number..." value={filters.passport} onChange={(v) => set("passport", v)} accent /><SearchField placeholder="Client Name..." value={filters.name} onChange={(v) => set("name", v)} /><SearchField placeholder="Phone number..." value={filters.phone} onChange={(v) => set("phone", v)} /><Select placeholder="Select Officer" value={filters.officer} options={(choices?.users ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("officer", v)} /><Select placeholder="Select Agent" value={filters.agent} options={(choices?.agents ?? []).map(asOption)} onChange={(v) => set("agent", v)} /><Select placeholder="Select Status" value={filters.status} options={["Pending", "Submitted", "Approved", "Rejected", "Done", ...(choices?.statuses ?? [])].filter(unique).map(asOption)} onChange={(v) => set("status", v)} /><Select placeholder="Select Loan Need" value={filters.loanNeeded} options={yesNo} onChange={(v) => set("loanNeeded", v)} /><Select placeholder="Select Office" value={filters.office} options={(choices?.offices ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("office", v)} /><Select placeholder="Ready to Flight" value={filters.readyToFlight} options={yesNo} onChange={(v) => set("readyToFlight", v)} /><Select placeholder="Select BMET Finger" value={filters.bmetFinger} options={yesNo} onChange={(v) => set("bmetFinger", v)} /><Select placeholder="Select BMET Training" value={filters.bmetTraining} options={yesNo} onChange={(v) => set("bmetTraining", v)} /><fieldset className="manpower-payment"><legend>Second payment (sum received)</legend><label><input type="radio" name="paymentBucket" checked={filters.paymentBucket === "Below"} onChange={() => set("paymentBucket", "Below")} />Below 150,000</label><label><input type="radio" name="paymentBucket" checked={filters.paymentBucket === "At Least"} onChange={() => set("paymentBucket", "At Least")} />150,000 or more</label></fieldset><div className="manpower-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>
    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Manpower records could not be loaded.</div>}<div className="manpower-toolbar"><button onClick={download}><Download size={16} />Download</button><div><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b> of <b>{meta.total}</b> Results</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select></div></div><div className="manpower-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Client Information</th><th>Status</th><th>Reference</th><th>Profession</th><th>Company</th><th>Agent</th><th>Officer</th><th>Office</th><th>Loan Needed</th><th>BMET Finger</th><th>BMET Training</th><th>Ready To Flight</th><th>Second Payment</th><th>Visa Status</th><th>Submitted</th><th>Approved</th><th>Quantity</th><th>Remarks</th><th>Document</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.manpowerId}><td>{(page - 1) * pageSize + index + 1}</td><td><Link href={`/file/${row.id}`}>Actions</Link></td><td className="client-info"><b>{row.name}</b><Link href={`/file/${row.id}`}>{row.candidateNo}</Link><span>{row.phone}</span><small>{row.passportNumber}</small></td><td><Badge value={row.status} good={/approved|done/i.test(row.status)} /></td><td>{row.reference}</td><td>{row.profession}</td><td>{row.company}</td><td>{row.agent}</td><td>{row.officer}</td><td>{row.office}</td><td><Badge value={yes(row.loanNeeded)} good={!row.loanNeeded} /></td><td><Badge value={yes(row.bmetFinger)} good={row.bmetFinger} /></td><td><Badge value={yes(row.bmetTraining)} good={row.bmetTraining} /></td><td><Badge value={yes(row.readyToFlight)} good={row.readyToFlight} /></td><td>{row.secondPayment.toLocaleString()}</td><td>{row.visaStatus}</td><td>{dateLabel(row.submittedAt)}</td><td>{dateLabel(row.approvedAt)}</td><td>{row.quantity}</td><td>{row.remarks}</td><td>{row.document}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={21}>No data available in table</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div>
  </section></div>;
}

const yesNo = [["Yes", "Yes"], ["No", "No"]];
function SearchField({ placeholder, value, onChange, accent = false }: { placeholder: string; value: string; onChange: (value: string) => void; accent?: boolean }) { return <div className={`manpower-search ${accent ? "accent" : ""}`}><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <select aria-label={placeholder} value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>; }
function Badge({ value, good }: { value: string; good: boolean }) { return <span className={`manpower-badge ${good ? "good" : ""}`}>{value}</span>; }
function asOption(value: string) { return [value, value]; } function yes(value: boolean) { return value ? "Yes" : "No"; } function unique(value: string, index: number, array: string[]) { return array.indexOf(value) === index; }
