"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; policeId: string; candidateNo: string; name: string; phone: string; passportNumber: string; country: string; officer: string; office: string; company: string; profession: string; applicationNumber: string; applicationDate: string | null; issueDate: string | null; expiryDate: string | null; result: string; status: string; certificateKey: string };
type Data = { data: Row[]; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaPoliceClearancePage({ country = "Saudi" }: { country?: string }) {
  const countryLabel = country === "Saudi" ? "Saudi Arabia" : country;
  const [filters, setFilters] = useState({ passport: "", name: "", phone: "" }); const [applied, setApplied] = useState(filters); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [expanded, setExpanded] = useState<string[]>([]);
  const query = useQuery({ queryKey: ["ksa-police", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, ...applied, page: String(page), pageSize: String(pageSize) }); const response = await fetch(`/api/ksa/police-clearance?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load police clearance records"); return response.json() as Promise<Data>; } }); const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 };
  const download = () => { const q = (v: unknown) => `"${String(v ?? "").replaceAll('"', '""')}"`; const csv = [["SL", "Client", "Candidate No", "Phone", "Passport", "Country", "Application No", "Application Date", "Issue Date", "Expiry Date", "Result", "Status", "Officer", "Office", "Profession", "Company", "Certificate"].join(","), ...rows.map((r, i) => [i + 1, r.name, r.candidateNo, r.phone, r.passportNumber, r.country, r.applicationNumber, dateLabel(r.applicationDate), dateLabel(r.issueDate), dateLabel(r.expiryDate), r.result, r.status, r.officer, r.office, r.profession, r.company, r.certificateKey].map(q).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `${country.toLowerCase()}-police-clearance.csv`; a.click(); URL.revokeObjectURL(url); };
  return <div className="ksa-police-page"><header><div className="breadcrumb">Dashboard / {countryLabel} Police Clarence</div><h1>{countryLabel} Police Clarence</h1></header><section className="ksa-police-card"><div className="police-filter"><input className="accent" aria-label="Passport No" placeholder="Passport No" value={filters.passport} onChange={(e) => setFilters({ ...filters, passport: e.target.value })} /><input aria-label="Name" placeholder="Name" value={filters.name} onChange={(e) => setFilters({ ...filters, name: e.target.value })} /><div><input aria-label="Phone" placeholder="Phone" value={filters.phone} onChange={(e) => setFilters({ ...filters, phone: e.target.value })} /><button onClick={() => { setApplied(filters); setPage(1); }}>Filter</button></div></div><button className="police-download" onClick={download}><Download size={16} />Download</button>

    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Police clearance records could not be loaded.</div>}<div className="ksa-police-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Client information</th><th>Country</th><th>Passport</th><th>Application No.</th><th>Application Date</th><th>Issue Date</th><th>Expiry Date</th><th>Result</th><th>Status</th><th>Officer</th><th>Office</th><th>Profession</th><th>Company</th><th>Certificate</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r.policeId}><td>{(page - 1) * pageSize + i + 1}</td><td><Link href={`/file/${r.id}`}>Actions</Link></td><td className="client-info"><b>{r.name}</b><Link href={`/file/${r.id}`}>{r.candidateNo}</Link><span>{r.phone}</span>{expanded.includes(r.id) ? <><small>Passport: {r.passportNumber}</small><button onClick={() => setExpanded(expanded.filter((id) => id !== r.id))}>Show less</button></> : <button onClick={() => setExpanded([...expanded, r.id])}>Show more</button>}</td><td>{r.country}</td><td>{r.passportNumber}</td><td>{r.applicationNumber}</td><td>{dateLabel(r.applicationDate)}</td><td>{dateLabel(r.issueDate)}</td><td>{dateLabel(r.expiryDate)}</td><td>{r.result}</td><td><span className="police-status">{r.status}</span></td><td>{r.officer}</td><td>{r.office}</td><td>{r.profession}</td><td>{r.company}</td><td>{r.certificateKey}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={16}>No police clearance records match these filters.</td></tr>}</tbody></table></div><div className="police-footer"><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select><span>Showing {meta.total ? (page - 1) * pageSize + 1 : 0} to {Math.min(page * pageSize, meta.total)} of {meta.total} records</span></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div>
  </section></div>;
}
