"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; takamulId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officerName: string; officeId: string; office: string; company: string; status: string; reportStatus: string; examDate: string | null; presentDate: string | null; centerDistrict: string; doneBy: string; visaProfession: string; takamulProfession: string; registrationNumber: string; certificateNumber: string; remarks: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }>; statuses: string[]; reportStatuses: string[]; districts: string[]; doneBy: string[]; visaProfessions: string[]; takamulProfessions: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", office: "", status: "", reportStatus: "", examFrom: "", examTo: "", presentFrom: "", presentTo: "", centerDistrict: "", doneBy: "", visaProfession: "", takamulProfession: "" }; const option = (value: string) => ({ value, label: value });
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaTakamulPage({ country = "Saudi" }: { country?: string }) {
  const countryLabel = country === "Saudi" ? "Saudi Arabia" : country;
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [expanded, setExpanded] = useState<string[]>([]);
  const query = useQuery({ queryKey: ["ksa-takamul", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/takamul?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load Takamul records"); return response.json() as Promise<Data>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const f = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const download = () => { const q = (v: unknown) => `"${String(v ?? "").replaceAll('"', '""')}"`; const csv = [["SL", "Client", "Candidate No", "Phone", "Passport", "Officer", "Office", "Status", "Report", "Exam Date", "Present Date", "Center District", "Done By", "Visa Profession", "Takamul Profession", "Registration", "Certificate", "Company", "Remarks"].join(","), ...rows.map((r, i) => [i + 1, r.name, r.candidateNo, r.phone, r.passportNumber, r.officerName, r.office, r.status, r.reportStatus, dateLabel(r.examDate), dateLabel(r.presentDate), r.centerDistrict, r.doneBy, r.visaProfession, r.takamulProfession, r.registrationNumber, r.certificateNumber, r.company, r.remarks].map(q).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `${country.toLowerCase()}-takamul-list.csv`; a.click(); URL.revokeObjectURL(url); };
  return <div className="ksa-takamul-page"><header><div className="breadcrumb">Dashboard / {countryLabel} Takamul</div><h1>{countryLabel} Takamul</h1></header><section className="ksa-takamul-card">

    <div className="takamul-filters"><SearchField placeholder="Passport number..." value={filters.passport} onChange={(v) => set("passport", v)} accent /><SearchField placeholder="Client Name..." value={filters.name} onChange={(v) => set("name", v)} /><SearchField placeholder="Phone number..." value={filters.phone} onChange={(v) => set("phone", v)} /><Select placeholder="Select Officer" value={filters.officer} options={(f?.users ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(v) => set("officer", v)} /><Select placeholder="Select Office" value={filters.office} options={(f?.offices ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(v) => set("office", v)} /><Select placeholder="Select Takamul Status" value={filters.status} options={["Pending", "Scheduled", "Present", "Done", ...(f?.statuses ?? [])].filter(unique).map(option)} onChange={(v) => set("status", v)} /><Select placeholder="Select Takamul Report Status" value={filters.reportStatus} options={["Pending", "Waiting for Result", "Passed", "Failed", "Certificate Issued", ...(f?.reportStatuses ?? [])].filter(unique).map(option)} onChange={(v) => set("reportStatus", v)} /><Range label="Takamul exam date range" from={filters.examFrom} to={filters.examTo} onFrom={(v) => set("examFrom", v)} onTo={(v) => set("examTo", v)} /><Range label="Takamul present date range" from={filters.presentFrom} to={filters.presentTo} onFrom={(v) => set("presentFrom", v)} onTo={(v) => set("presentTo", v)} /><Select placeholder="Select Takamul Center District" value={filters.centerDistrict} options={(f?.districts ?? []).map(option)} onChange={(v) => set("centerDistrict", v)} /><Select placeholder="Select Takamul Done By" value={filters.doneBy} options={(f?.doneBy ?? []).map(option)} onChange={(v) => set("doneBy", v)} /><Select placeholder="Select Visa Profession" value={filters.visaProfession} options={(f?.visaProfessions ?? []).map(option)} onChange={(v) => set("visaProfession", v)} /><Select placeholder="Select Takamul Profession" value={filters.takamulProfession} options={(f?.takamulProfessions ?? []).map(option)} onChange={(v) => set("takamulProfession", v)} /><div className="takamul-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>
    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Takamul records could not be loaded.</div>}<div className="takamul-toolbar"><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b> to <b>{Math.min(page * pageSize, meta.total)}</b> of <b>{meta.total}</b> Results</span><div><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select><button onClick={download}><Download size={17} />Download</button></div></div>
    <div className="ksa-takamul-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Client information</th><th>Officer</th><th>Office</th><th>Takamul Status</th><th>Takamul Report</th><th>Takamul Exam Date</th><th>Present Date</th><th>Center District</th><th>Takamul Done By</th><th>Visa Profession</th><th>Takamul Profession</th><th>Registration No.</th><th>Certificate No.</th><th>Company</th><th>Remarks</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r.takamulId}><td>{(page - 1) * pageSize + i + 1}</td><td><Link href={`/file/${r.id}`}>Actions</Link></td><td className="client-info"><b>{r.name}</b><Link href={`/file/${r.id}`}>{r.candidateNo}</Link>{expanded.includes(r.id) ? <><span>Phone: {r.phone}</span><small>Passport: {r.passportNumber}</small><button onClick={() => setExpanded(expanded.filter((id) => id !== r.id))}>Show less</button></> : <button onClick={() => setExpanded([...expanded, r.id])}>Show more</button>}</td><td>{r.officerName}</td><td>{r.office}</td><td><Status value={r.status} /></td><td><Status value={r.reportStatus} /></td><td>{dateLabel(r.examDate)}</td><td>{dateLabel(r.presentDate)}</td><td>{r.centerDistrict}</td><td>{r.doneBy}</td><td>{r.visaProfession}</td><td>{r.takamulProfession}</td><td>{r.registrationNumber}</td><td>{r.certificateNumber}</td><td>{r.company}</td><td>{r.remarks}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={17}>No Takamul records match these filters.</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} />Previous</button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}>Next<ChevronRight size={16} /></button></div>
  </section></div>;
}

function SearchField({ placeholder, value, onChange, accent = false }: { placeholder: string; value: string; onChange: (v: string) => void; accent?: boolean }) { return <div className={`takamul-search ${accent ? "accent" : ""}`}><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: Array<{ value: string; label: string }>; onChange: (v: string) => void }) { return <select aria-label={placeholder} value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select>; }
function Range({ label, from, to, onFrom, onTo }: { label: string; from: string; to: string; onFrom: (v: string) => void; onTo: (v: string) => void }) { return <label className="takamul-range"><span>{label}</span><div><input aria-label={`${label} from`} type="date" value={from} onChange={(e) => onFrom(e.target.value)} /><input aria-label={`${label} to`} type="date" value={to} onChange={(e) => onTo(e.target.value)} /></div></label>; }
function Status({ value }: { value: string }) { return <span className={/present|pass|done|certificate/i.test(value) ? "takamul-status green" : "takamul-status"}>{value}</span>; }
function unique(value: string, index: number, array: string[]) { return array.indexOf(value) === index; }
