"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; eventId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officer: string; officeId: string; office: string; source: string; company: string; profession: string; paymentStatus: string; manpowerStatus: string; acDone: boolean; loanNeeded: boolean; loanClear: boolean; bmetFinger: boolean; bmetTraining: boolean; readiness: string; readyDate: string | null; blockers: string; remarks: string; visaStatus: string; visaExpiry: string | null; flightStatus: string; flightDate: string | null; airline: string; flightName: string; location: string; groupName: string; returnedAfterFlight: boolean };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }>; paymentStatuses: string[]; manpowerStatuses: string[]; flightStatuses: string[] }; meta: { page: number; pageSize: number; total: number; returnedAfterFlight: number; totalPages: number } };
const blank = { passport: "", name: "", officer: "", office: "", phone: "", paymentStatus: "", manpowerStatus: "", acDone: "", loanNeeded: "", flightStatus: "", bmetFinger: "", bmetTraining: "", flightFrom: "", flightTo: "", visaFrom: "", visaTo: "", airline: "", flightName: "", location: "", groupName: "" };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaReadyFlightPage({ country = "Saudi" }: { country?: string }) {
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const query = useQuery({ queryKey: ["ksa-ready-flight", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/ready-flight?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load ready-to-flight records"); return response.json() as Promise<Data>; } }); const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, returnedAfterFlight: 0, totalPages: 1 }; const choices = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const download = () => { const q = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = [["SL", "Source", "Client", "Candidate", "Phone", "Passport", "Readiness", "Payment", "Manpower", "AC", "Loan", "BMET Finger", "BMET Training", "Visa", "Visa Expiry", "Flight", "Flight Date", "Airline", "Location", "Group", "Officer", "Office"].join(","), ...rows.map((row, index) => [index + 1, row.source, row.name, row.candidateNo, row.phone, row.passportNumber, row.readiness, row.paymentStatus, row.manpowerStatus, yes(row.acDone), yes(row.loanNeeded), yes(row.bmetFinger), yes(row.bmetTraining), row.visaStatus, dateLabel(row.visaExpiry), row.flightName, dateLabel(row.flightDate), row.airline, row.location, row.groupName, row.officer, row.office].map(q).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "ready-to-flight.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="ksa-ready-page"><header><div className="breadcrumb">Dashboard / Ready To Flight</div><h1>Ready To Flight</h1></header><section className="ready-card"><div className="ready-filters"><SearchField placeholder="Passport number..." value={filters.passport} onChange={(v) => set("passport", v)} accent /><SearchField placeholder="Client Name..." value={filters.name} onChange={(v) => set("name", v)} /><Select placeholder="Select Officer" value={filters.officer} options={(choices?.users ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("officer", v)} /><Select placeholder="Select Office" value={filters.office} options={(choices?.offices ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("office", v)} /><SearchField placeholder="Phone number..." value={filters.phone} onChange={(v) => set("phone", v)} /><Select placeholder="Select Payment Status" value={filters.paymentStatus} options={(choices?.paymentStatuses ?? []).map(asOption)} onChange={(v) => set("paymentStatus", v)} /><Select placeholder="Select Manpower Status" value={filters.manpowerStatus} options={(choices?.manpowerStatuses ?? []).map(asOption)} onChange={(v) => set("manpowerStatus", v)} /><Select placeholder="Select AC Done" value={filters.acDone} options={yesNo} onChange={(v) => set("acDone", v)} /><Select placeholder="Select Loan Need" value={filters.loanNeeded} options={yesNo} onChange={(v) => set("loanNeeded", v)} /><Select placeholder="All Flight Status" value={filters.flightStatus} options={["Not Scheduled", "Scheduled", "Flown", "Cancelled", ...(choices?.flightStatuses ?? [])].filter(unique).map(asOption)} onChange={(v) => set("flightStatus", v)} /><Select placeholder="Select BMET Finger" value={filters.bmetFinger} options={yesNo} onChange={(v) => set("bmetFinger", v)} /><Select placeholder="Select BMET Training" value={filters.bmetTraining} options={yesNo} onChange={(v) => set("bmetTraining", v)} /><DateRange placeholder="Flight date or range" from={filters.flightFrom} to={filters.flightTo} onFrom={(v) => set("flightFrom", v)} onTo={(v) => set("flightTo", v)} /><DateRange placeholder="Visa Expire date or range" from={filters.visaFrom} to={filters.visaTo} onFrom={(v) => set("visaFrom", v)} onTo={(v) => set("visaTo", v)} /><SearchField placeholder="Airplane Name..." value={filters.airline} onChange={(v) => set("airline", v)} /><SearchField placeholder="Flight Name..." value={filters.flightName} onChange={(v) => set("flightName", v)} /><SearchField placeholder="Location..." value={filters.location} onChange={(v) => set("location", v)} /><SearchField placeholder="Group Name..." value={filters.groupName} onChange={(v) => set("groupName", v)} /><div className="ready-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>
    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Ready-to-flight records could not be loaded.</div>}<div className="ready-toolbar"><button onClick={download}><Download size={16} />Download</button><div><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b> of <b>{meta.total}</b> Results</span><label>Per page<select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select></label></div></div><div className="returned-count">{meta.returnedAfterFlight} file(s) returned from After Flight</div><div className="ready-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Source</th><th>Client Information</th><th>Readiness</th><th>Payment</th><th>Manpower</th><th>AC Done</th><th>Loan Need</th><th>BMET Finger</th><th>BMET Training</th><th>Visa Status</th><th>Visa Expiry</th><th>Flight Status</th><th>Flight Name</th><th>Flight Date</th><th>Airplane</th><th>Location</th><th>Group</th><th>Officer</th><th>Office</th><th>Company</th><th>Profession</th><th>Blockers</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.eventId}><td>{(page - 1) * pageSize + index + 1}</td><td><Link href={`/file/${row.id}`}>Actions</Link></td><td>{row.source}</td><td className="client-info"><b>{row.name}</b><Link href={`/file/${row.id}`}>{row.candidateNo}</Link><span>{row.phone}</span><small>{row.passportNumber}</small></td><td><Badge value={row.readiness} good={/ready/i.test(row.readiness)} /></td><td>{row.paymentStatus}</td><td>{row.manpowerStatus}</td><td>{yes(row.acDone)}</td><td>{yes(row.loanNeeded)}</td><td><Badge value={yes(row.bmetFinger)} good={row.bmetFinger} /></td><td><Badge value={yes(row.bmetTraining)} good={row.bmetTraining} /></td><td>{row.visaStatus}</td><td>{dateLabel(row.visaExpiry)}</td><td>{row.flightStatus}</td><td>{row.flightName}</td><td>{dateLabel(row.flightDate)}</td><td>{row.airline}</td><td>{row.location}</td><td>{row.groupName}</td><td>{row.officer}</td><td>{row.office}</td><td>{row.company}</td><td>{row.profession}</td><td>{row.blockers}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={24}>No data available in table</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div>
  </section></div>;
}

const yesNo = [["Yes", "Yes"], ["No", "No"]];
function SearchField({ placeholder, value, onChange, accent = false }: { placeholder: string; value: string; onChange: (value: string) => void; accent?: boolean }) { return <div className={`ready-search ${accent ? "accent" : ""}`}><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <select aria-label={placeholder} value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>; }
function DateRange({ placeholder, from, to, onFrom, onTo }: { placeholder: string; from: string; to: string; onFrom: (value: string) => void; onTo: (value: string) => void }) { return <label className="ready-date"><span>{placeholder}</span><div><input aria-label={`${placeholder} from`} type="date" value={from} onChange={(e) => onFrom(e.target.value)} /><input aria-label={`${placeholder} to`} type="date" value={to} onChange={(e) => onTo(e.target.value)} /></div></label>; }
function Badge({ value, good }: { value: string; good: boolean }) { return <span className={`ready-badge ${good ? "good" : ""}`}>{value}</span>; } function asOption(value: string) { return [value, value]; } function yes(value: boolean) { return value ? "Yes" : "No"; } function unique(value: string, index: number, array: string[]) { return array.indexOf(value) === index; }
