"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; holdId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officer: string; profession: string; company: string; source: string; customerStatus: string; officeStatus: string; remarks: string; reason: string; createdAt: string; expectedRelease: string | null; owner: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; professions: string[]; companies: string[]; sources: string[]; customerStatuses: string[]; officeStatuses: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", phone: "", name: "", officer: "", profession: "", company: "", source: "", customerStatus: "", officeStatus: "", remarks: "", createdFrom: "", createdTo: "" };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaVisaHoldPage({ country = "Saudi", title }: { country?: string; title?: string }) {
  const countryLabel = country === "Saudi" ? "Saudi Arabia" : country;
  const pageTitle = title || `${countryLabel} E-Visa Hold`;
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25);
  const query = useQuery({ queryKey: ["ksa-visa-hold", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/visa-hold?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load E-Visa Hold records"); return response.json() as Promise<Data>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const choices = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  return <div className="ksa-visa-hold-page"><header><div className="breadcrumb">Dashboard / {pageTitle}</div><h1>{pageTitle}</h1></header><section className="visa-hold-card"><div className="visa-hold-filters"><Field label="Passport"><input className="accent" placeholder="Passport no" value={filters.passport} onChange={(e) => set("passport", e.target.value)} /></Field><Field label="Phone"><input placeholder="Phone" value={filters.phone} onChange={(e) => set("phone", e.target.value)} /></Field><Field label="Client name"><input placeholder="Name" value={filters.name} onChange={(e) => set("name", e.target.value)} /></Field><Field label="Officer"><Select placeholder="Officer" value={filters.officer} options={(choices?.users ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("officer", v)} /></Field><Field label="Profession"><Select placeholder="All professions" value={filters.profession} options={(choices?.professions ?? []).map(asOption)} onChange={(v) => set("profession", v)} /></Field><Field label="Company"><Select placeholder="All companies" value={filters.company} options={(choices?.companies ?? []).map(asOption)} onChange={(v) => set("company", v)} /></Field><Field label="Source"><Select placeholder="All sources" value={filters.source} options={(choices?.sources ?? []).map(asOption)} onChange={(v) => set("source", v)} /></Field><Field label="Customer status"><Select placeholder="All" value={filters.customerStatus} options={(choices?.customerStatuses ?? []).map(asOption)} onChange={(v) => set("customerStatus", v)} /></Field><Field label="Office status"><Select placeholder="All" value={filters.officeStatus} options={(choices?.officeStatuses ?? []).map(asOption)} onChange={(v) => set("officeStatus", v)} /></Field><Field label="Remarks"><input placeholder="Search remarks" value={filters.remarks} onChange={(e) => set("remarks", e.target.value)} /></Field><Field label="Created from"><input aria-label="Created from" type="date" value={filters.createdFrom} onChange={(e) => set("createdFrom", e.target.value)} /></Field><Field label="Created to"><input aria-label="Created to" type="date" value={filters.createdTo} onChange={(e) => set("createdTo", e.target.value)} /></Field><div className="visa-hold-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply filter</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>

    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">E-Visa Hold records could not be loaded.</div>}<div className="visa-hold-table"><table><thead><tr><th>SL</th><th>Actions</th><th>Client Information</th><th>Passport</th><th>Profession</th><th>Company</th><th>Source</th><th>Customer Status</th><th>Office Status</th><th>Hold Reason</th><th>Remarks</th><th>Officer</th><th>Owner</th><th>Created</th><th>Expected Release</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.holdId}><td>{(page - 1) * pageSize + index + 1}</td><td><Link href={`/file/${row.id}`}>Actions</Link></td><td className="client-info"><b>{row.name}</b><Link href={`/file/${row.id}`}>{row.candidateNo}</Link><span>{row.phone}</span></td><td>{row.passportNumber}</td><td>{row.profession}</td><td>{row.company}</td><td>{row.source}</td><td><span className="hold-badge customer">{row.customerStatus}</span></td><td><span className="hold-badge">{row.officeStatus}</span></td><td>{row.reason}</td><td>{row.remarks}</td><td>{row.officer}</td><td>{row.owner}</td><td>{dateLabel(row.createdAt)}</td><td>{dateLabel(row.expectedRelease)}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={15}>No data available in table</td></tr>}</tbody></table></div><footer className="visa-hold-footer"><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>25</option><option>50</option></select><span>{meta.total ? `Showing ${(page - 1) * pageSize + 1} to ${Math.min(page * pageSize, meta.total)} of ${meta.total} records` : "Showing no records"}</span><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div></footer>
  </section></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span>{label}</span>{children}</label>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <select value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>; }
function asOption(value: string) { return [value, value]; }
