"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, FileDown, Search, Upload } from "lucide-react";
import Link from "next/link";
import { useRef, useState } from "react";

type Row = { id: string; biometricId: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officerName: string; officeId: string; office: string; company: string; profession: string; status: string; fingerDate: string | null; appointmentDate: string | null; presentDate: string | null; completedAt: string | null; firstPaymentStatus: string; firstPaymentAmount: number; mofaStatus: string; mofaDoneDate: string | null; evidenceKey: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }>; statuses: string[]; paymentStatuses: string[]; mofaStatuses: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", office: "", status: "", paymentStatus: "", mofaStatus: "", mofaFrom: "", mofaTo: "", fingerFrom: "", fingerTo: "" }; const option = (value: string) => ({ value, label: value });
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaBioFingerPage({ country = "Saudi" }: { country?: string }) {
  const countryLabel = country === "Saudi" ? "Saudi Arabia" : country;
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [message, setMessage] = useState(""); const [expanded, setExpanded] = useState<string[]>([]); const inputRef = useRef<HTMLInputElement>(null); const client = useQueryClient();
  const query = useQuery({ queryKey: ["ksa-bio-finger", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/bio-finger?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load Bio Finger records"); return response.json() as Promise<Data>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const f = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const download = (sample = false) => { const q = (v: unknown) => `"${String(v ?? "").replaceAll('"', '""')}"`; const content = sample ? ["fileNo,candidateNo,passportNumber,status,appointmentDate,presentDate,completedAt,evidenceKey", "FILE-001,,,Pending,2026-08-10,,,"] : [["SL", "Client", "Candidate No", "Phone", "Passport", "Status", "Finger Date", "Appointment", "Present", "Completed", "Officer", "Office", "First Payment", "Amount", "MOFA Status", "MOFA Done", "Profession", "Company", "Evidence"].join(","), ...rows.map((r, i) => [i + 1, r.name, r.candidateNo, r.phone, r.passportNumber, r.status, dateLabel(r.fingerDate), dateLabel(r.appointmentDate), dateLabel(r.presentDate), dateLabel(r.completedAt), r.officerName, r.office, r.firstPaymentStatus, r.firstPaymentAmount, r.mofaStatus, dateLabel(r.mofaDoneDate), r.profession, r.company, r.evidenceKey].map(q).join(","))]; saveCsv(content.join("\n"), sample ? "bio-finger-sample.csv" : `${country.toLowerCase()}-bio-finger-list.csv`); };
  const upload = async (file?: File) => { if (!file) return; setMessage("Uploading CSV..."); try { const response = await fetch(`/api/ksa/bio-finger?country=${encodeURIComponent(country)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows: parseCsv(await file.text()) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Upload failed"); setMessage(`${result.data.imported} Bio Finger record(s) imported${result.data.errors.length ? `; ${result.data.errors.length} skipped` : ""}.`); await client.invalidateQueries({ queryKey: ["ksa-bio-finger"] }); await client.invalidateQueries({ queryKey: ["ksa-queue-counts"] }); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed"); } finally { if (inputRef.current) inputRef.current.value = ""; } };
  return <div className="ksa-bio-page"><header><div className="breadcrumb">Dashboard / {countryLabel} Bio Finger File</div><h1>{countryLabel} Bio Finger File</h1></header><section className="ksa-bio-card"><div className="bio-filters"><SearchField placeholder="Passport number..." value={filters.passport} onChange={(v) => set("passport", v)} accent /><SearchField placeholder="Client Name..." value={filters.name} onChange={(v) => set("name", v)} /><SearchField placeholder="Phone number..." value={filters.phone} onChange={(v) => set("phone", v)} /><Select placeholder="Select Officer" value={filters.officer} options={(f?.users ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(v) => set("officer", v)} /><Select placeholder="Select Office" value={filters.office} options={(f?.offices ?? []).map((x) => ({ value: x.id, label: x.name }))} onChange={(v) => set("office", v)} /><Select placeholder="Select Ksa Status" value={filters.status} options={["Pending", "Appointment", "Present", "Done", "Failed", ...(f?.statuses ?? [])].filter(unique).map(option)} onChange={(v) => set("status", v)} /><Select placeholder="First Payment Status (50,000)" value={filters.paymentStatus} options={(f?.paymentStatuses ?? []).map(option)} onChange={(v) => set("paymentStatus", v)} /><Select placeholder="Select MOFA Status" value={filters.mofaStatus} options={(f?.mofaStatuses ?? []).map(option)} onChange={(v) => set("mofaStatus", v)} /><Range label="MOFA done date range" from={filters.mofaFrom} to={filters.mofaTo} onFrom={(v) => set("mofaFrom", v)} onTo={(v) => set("mofaTo", v)} /><Range label="Filter by finger date range" from={filters.fingerFrom} to={filters.fingerTo} onFrom={(v) => set("fingerFrom", v)} onTo={(v) => set("fingerTo", v)} /><div className="bio-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>

    {message && <div className="mofa-message">{message}</div>}{query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">KSA Bio Finger records could not be loaded.</div>}<div className="bio-toolbar"><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b>–<b>{Math.min(page * pageSize, meta.total)}</b> of <b>{meta.total}</b> ({pageSize} per page)</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select></div><div className="bio-csv"><button onClick={() => download(true)}><FileDown size={16} />Sample CSV</button><button onClick={() => inputRef.current?.click()}><Upload size={16} />Upload CSV</button><button onClick={() => download()}><Download size={16} />Download CSV</button><input hidden ref={inputRef} type="file" accept=".csv,text/csv" onChange={(e) => upload(e.target.files?.[0])} /></div>
    <div className="ksa-bio-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Client</th><th>Status</th><th>Finger Date</th><th>Appointment Date</th><th>Present Date</th><th>Completed Date</th><th>Officer</th><th>Office</th><th>First Payment</th><th>Amount</th><th>MOFA Status</th><th>MOFA Done Date</th><th>Profession</th><th>Company</th><th>Evidence</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r.biometricId}><td>{(page - 1) * pageSize + i + 1}</td><td><Link href={`/file/${r.id}`}>Actions</Link></td><td className="client-info"><b>{r.name}</b><Link href={`/file/${r.id}`}>{r.candidateNo}</Link>{expanded.includes(r.id) ? <><span>Phone: {r.phone}</span><small>Passport: {r.passportNumber}</small><button onClick={() => setExpanded(expanded.filter((id) => id !== r.id))}>Show less</button></> : <button onClick={() => setExpanded([...expanded, r.id])}>Show more</button>}</td><td><span className="bio-status">{r.status}</span></td><td>{dateLabel(r.fingerDate)}</td><td>{dateLabel(r.appointmentDate)}</td><td>{dateLabel(r.presentDate)}</td><td>{dateLabel(r.completedAt)}</td><td>{r.officerName}</td><td>{r.office}</td><td>{r.firstPaymentStatus}</td><td>{r.firstPaymentAmount.toLocaleString()}</td><td>{r.mofaStatus}</td><td>{dateLabel(r.mofaDoneDate)}</td><td>{r.profession}</td><td>{r.company}</td><td>{r.evidenceKey}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={17}>No KSA Bio Finger records match these filters.</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} />Previous</button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}>Next<ChevronRight size={16} /></button></div>
  </section></div>;
}

function SearchField({ placeholder, value, onChange, accent = false }: { placeholder: string; value: string; onChange: (v: string) => void; accent?: boolean }) { return <div className={`bio-search ${accent ? "accent" : ""}`}><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: Array<{ value: string; label: string }>; onChange: (v: string) => void }) { return <select aria-label={placeholder} value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select>; }
function Range({ label, from, to, onFrom, onTo }: { label: string; from: string; to: string; onFrom: (v: string) => void; onTo: (v: string) => void }) { return <label className="bio-range"><span>{label}</span><div><input aria-label={`${label} from`} type="date" value={from} onChange={(e) => onFrom(e.target.value)} /><input aria-label={`${label} to`} type="date" value={to} onChange={(e) => onTo(e.target.value)} /></div></label>; }
function unique(value: string, index: number, array: string[]) { return array.indexOf(value) === index; }
function saveCsv(content: string, name: string) { const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function parseCsv(text: string) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error("CSV contains no data rows."); const parse = (line: string) => { const result: string[] = []; let value = "", quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"' && quoted && line[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { result.push(value.trim()); value = ""; } else value += char; } result.push(value.trim()); return result; }; const headers = parse(lines[0]); return lines.slice(1).map((line) => { const values = parse(line); return Object.fromEntries(headers.map((header, i) => [header, values[i] ?? ""])); }); }
