"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, FileDown, Search, Upload } from "lucide-react";
import Link from "next/link";
import { useRef, useState } from "react";

type Row = { id: string; visaId: string; fileNo: string; candidateNo: string; name: string; phone: string; age: number | null; passportNumber: string; officerId: string; officerName: string; officeId: string; office: string; company: string; status: string; fitCardStatus: string; visaNumber: string; visaType: string; profession: string; submissionDate: string | null; issueDate: string | null; stampingDate: string | null; expiryDate: string | null; document: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }>; statuses: string[]; fitCardStatuses: string[]; professions: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", status: "", fitCardStatus: "", office: "", submitFrom: "", submitTo: "", issueFrom: "", issueTo: "", expiryFrom: "", expiryTo: "", profession: "" };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaVisaStampingPage({ country = "Saudi", title = "Visa Stamping", initialStatus = "" }: { country?: string; title?: string; initialStatus?: string }) {
  const defaultFilters = { ...blank, status: initialStatus };
  const [filters, setFilters] = useState(defaultFilters); const [applied, setApplied] = useState(defaultFilters); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [message, setMessage] = useState(""); const inputRef = useRef<HTMLInputElement>(null); const client = useQueryClient();
  const query = useQuery({ queryKey: ["ksa-visa-stamping", country, initialStatus, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/visa-stamping?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load E-Visa records"); return response.json() as Promise<Data>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const choices = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const download = (sample = false) => { const q = (v: unknown) => `"${String(v ?? "").replaceAll('"', '""')}"`; const content = sample ? "fileNo,candidateNo,passportNumber,status,visaNumber,visaType,profession,submissionDate,issueDate,stampingDate,expiryDate\nFILE-001,,,Submitted,,,Bike Rider,2026-08-01,,," : [["SL", "Status", "Client", "Candidate No", "Phone", "Age", "Passport", "Fit Card", "Submit Date", "Issue Date", "Stamping Date", "Expiry Date", "Visa No", "Visa Type", "Visa Profession", "Officer", "Office", "Company", "Document"].join(","), ...rows.map((r, i) => [i + 1, r.status, r.name, r.candidateNo, r.phone, r.age ?? "N/A", r.passportNumber, r.fitCardStatus, dateLabel(r.submissionDate), dateLabel(r.issueDate), dateLabel(r.stampingDate), dateLabel(r.expiryDate), r.visaNumber, r.visaType, r.profession, r.officerName, r.office, r.company, r.document].map(q).join(","))].join("\n"); saveCsv(content, sample ? "e-visa-stamping-sample.csv" : "e-visa-stamping.csv"); };
  const upload = async (file?: File) => { if (!file) return; setMessage("Uploading CSV..."); try { const response = await fetch(`/api/ksa/visa-stamping?country=${encodeURIComponent(country)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows: parseCsv(await file.text()) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? "Upload failed"); setMessage(`${result.data.imported} E-Visa record(s) imported${result.data.errors.length ? `; ${result.data.errors.length} skipped` : ""}.`); await client.invalidateQueries({ queryKey: ["ksa-visa-stamping"] }); await client.invalidateQueries({ queryKey: ["ksa-queue-counts"] }); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed"); } finally { if (inputRef.current) inputRef.current.value = ""; } };
  return <div className="ksa-visa-page"><header><div className="breadcrumb">Dashboard / {title}</div><h1>{title}</h1></header><section className="visa-card"><div className="visa-filters"><SearchField placeholder="Passport number..." value={filters.passport} onChange={(v) => set("passport", v)} accent /><SearchField placeholder="Client Name..." value={filters.name} onChange={(v) => set("name", v)} /><SearchField placeholder="Phone number..." value={filters.phone} onChange={(v) => set("phone", v)} /><Select placeholder="Select Officer" value={filters.officer} options={(choices?.users ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("officer", v)} /><Select placeholder="Select E-visa status" value={filters.status} options={["Pending", "Submitted", "Stamped", "Rejected", "Done", ...(choices?.statuses ?? [])].filter(unique).map((x) => [x, x])} onChange={(v) => set("status", v)} /><Select placeholder="Select Fit Card Status" value={filters.fitCardStatus} options={(choices?.fitCardStatuses ?? []).map((x) => [x, x])} onChange={(v) => set("fitCardStatus", v)} /><Select placeholder="Select Office" value={filters.office} options={(choices?.offices ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("office", v)} /><DateRange label="E-visa submit date range" from={filters.submitFrom} to={filters.submitTo} onFrom={(v) => set("submitFrom", v)} onTo={(v) => set("submitTo", v)} /><DateRange label="E-visa Issue Date Range" from={filters.issueFrom} to={filters.issueTo} onFrom={(v) => set("issueFrom", v)} onTo={(v) => set("issueTo", v)} /><DateRange label="E-visa Expire Date Range" from={filters.expiryFrom} to={filters.expiryTo} onFrom={(v) => set("expiryFrom", v)} onTo={(v) => set("expiryTo", v)} /><Select placeholder="Select Visa Profession" value={filters.profession} options={(choices?.professions ?? []).map((x) => [x, x])} onChange={(v) => set("profession", v)} /><div className="visa-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(defaultFilters); setApplied(defaultFilters); setPage(1); }}>Clear</button></div></div>
    {message && <div className="mofa-message">{message}</div>}{query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">E-Visa records could not be loaded.</div>}<div className="visa-csv"><button onClick={() => download(true)}><FileDown size={16} />Download Sample CSV</button><button onClick={() => inputRef.current?.click()}><Upload size={16} />Upload CSV</button><button onClick={() => download()}><Download size={16} />Download</button><input hidden ref={inputRef} type="file" accept=".csv,text/csv" onChange={(e) => upload(e.target.files?.[0])} /></div><div className="visa-summary"><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b>–<b>{Math.min(page * pageSize, meta.total)}</b> of <b>{meta.total}</b> Results</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select></div>
    <div className="visa-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Status</th><th>Client Information</th><th>Fit Card</th><th>E-Visa Submit</th><th>E-Visa Issue</th><th>E-Visa Stamping</th><th>E-Visa Expiry</th><th>Visa Number</th><th>Visa Type</th><th>Visa Profession</th><th>Officer</th><th>Office</th><th>Company</th><th>Document</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r.visaId}><td>{(page - 1) * pageSize + i + 1}</td><td><Link href={`/file/${r.id}`}>Actions</Link></td><td><span className="visa-status">{r.status === "Submitted" ? "E-VISA SUBMIT" : r.status.toUpperCase()}</span></td><td className="client-info"><b>{r.name}</b><Link href={`/file/${r.id}`}>{r.candidateNo}</Link><span>Passport: {r.passportNumber}</span><span>Phone: {r.phone}</span><small>Age: {r.age ?? "N/A"} Years</small></td><td><span className={`fit-card ${isDone(r.fitCardStatus) ? "done" : ""}`}>{r.fitCardStatus.toUpperCase()}</span></td><td>{dateLabel(r.submissionDate)}</td><td>{dateLabel(r.issueDate)}</td><td>{dateLabel(r.stampingDate)}</td><td>{dateLabel(r.expiryDate)}</td><td>{r.visaNumber}</td><td>{r.visaType}</td><td>{r.profession}</td><td>{r.officerName}</td><td>{r.office}</td><td>{r.company}</td><td>{r.document}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={16}>No E-Visa stamping records match these filters.</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div>
  </section></div>;
}

function SearchField({ placeholder, value, onChange, accent = false }: { placeholder: string; value: string; onChange: (value: string) => void; accent?: boolean }) { return <div className={`visa-search ${accent ? "accent" : ""}`}><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} /></div>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <select aria-label={placeholder} value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>; }
function DateRange({ label, from, to, onFrom, onTo }: { label: string; from: string; to: string; onFrom: (value: string) => void; onTo: (value: string) => void }) { return <label className="visa-range"><span>{label}</span><div><input aria-label={`${label} from`} type="date" value={from} onChange={(e) => onFrom(e.target.value)} /><input aria-label={`${label} to`} type="date" value={to} onChange={(e) => onTo(e.target.value)} /></div></label>; }
function isDone(value: string) { return /done|fit|received/i.test(value); }
function unique(value: string, index: number, array: string[]) { return array.indexOf(value) === index; }
function saveCsv(content: string, name: string) { const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
function parseCsv(text: string) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean); if (lines.length < 2) throw new Error("CSV contains no data rows."); const parse = (line: string) => { const result: string[] = []; let value = "", quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"' && quoted && line[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { result.push(value.trim()); value = ""; } else value += char; } result.push(value.trim()); return result; }; const headers = parse(lines[0]); return lines.slice(1).map((line) => Object.fromEntries(headers.map((header, index) => [header, parse(line)[index] ?? ""]))); }
