"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Filter } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; country: string; officerId: string; officer: string; officeId: string; office: string; company: string; profession: string; status: string; paymentStatus: string; medicalStatus: string; mofaStatus: string; takamulStatus: string; bioStatus: string; policeStatus: string; reMedical: boolean; reMofa: boolean; updatedAt: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }> }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", office: "", paymentStatus: "" }; const dateLabel = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));

export function KsaPreConfirmPage({ country = "Saudi", title = "Confirm File", stage = "Pre Confirm File" }: { country?: string; title?: string; stage?: string }) {
  const [open, setOpen] = useState(false); const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const query = useQuery({ queryKey: ["ksa-pre-confirm", country, stage, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, stage, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/pre-confirm?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load pre-confirm files"); return response.json() as Promise<Data>; } }); const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const f = query.data?.filters;
  return <div className="ksa-pre-confirm-page"><header><div className="breadcrumb">Dashboard / {title}</div><h1>{title}</h1></header><section className="pre-confirm-card"><button className="pre-toggle" onClick={() => setOpen(!open)}><Filter size={18} />Show/Hide Filters</button>{open && <div className="pre-filters"><input placeholder="Passport number..." value={filters.passport} onChange={(e) => setFilters({ ...filters, passport: e.target.value })} /><input placeholder="Client name..." value={filters.name} onChange={(e) => setFilters({ ...filters, name: e.target.value })} /><input placeholder="Phone number..." value={filters.phone} onChange={(e) => setFilters({ ...filters, phone: e.target.value })} /><select value={filters.officer} onChange={(e) => setFilters({ ...filters, officer: e.target.value })}><option value="">Select Officer</option>{(f?.users ?? []).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={filters.office} onChange={(e) => setFilters({ ...filters, office: e.target.value })}><option value="">Select Office</option>{(f?.offices ?? []).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={filters.paymentStatus} onChange={(e) => setFilters({ ...filters, paymentStatus: e.target.value })}><option value="">First Payment Status</option>{["PENDING", "PARTIAL", "PAID", "OVERDUE"].map((x) => <option key={x}>{x}</option>)}</select><div><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>}
    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Pre-confirm files could not be loaded.</div>}<div className="pre-summary"><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select><b>SHOWING {meta.total ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, meta.total)} OF {meta.total} TOTAL ({pageSize} PER PAGE)</b></div><div className="pre-confirm-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>File Type</th><th>Client information</th><th>Country</th><th>Passport</th><th>First Payment</th><th>Medical</th><th>MOFA</th><th>Takamul</th><th>KSA Bio</th><th>Police</th><th>Officer</th><th>Office</th><th>Profession</th><th>Company</th><th>Last Updated</th></tr></thead><tbody>{rows.map((r, i) => <tr key={r.id}><td>{(page - 1) * pageSize + i + 1}</td><td><Link href={`/file/${r.id}`}>Actions</Link></td><td><div className="pre-types">{fileTypes(r).map((x) => <span key={x}>{x}</span>)}</div></td><td className="client-info"><b>{r.name}</b><Link href={`/file/${r.id}`}>{r.candidateNo}</Link><span>{r.phone}</span></td><td>{r.country}</td><td>{r.passportNumber}</td><td>{r.paymentStatus}</td><td>{r.medicalStatus}</td><td>{r.mofaStatus}</td><td>{r.takamulStatus}</td><td>{r.bioStatus}</td><td>{r.policeStatus}</td><td>{r.officer}</td><td>{r.office}</td><td>{r.profession}</td><td>{r.company}</td><td>{dateLabel(r.updatedAt)}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={17}>No pre-confirm files available.</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div>
  </section></div>;
}
function fileTypes(row: Row) { return row.reMedical || row.reMofa ? [...(row.reMedical ? ["RE-MEDICAL"] : []), ...(row.reMofa ? ["RE-MOFA"] : [])] : ["NORMAL"]; }
