"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type MedicalRow = { id: string; medicalId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officerName: string; officeId: string; office: string; company: string; profession: string; status: string; reportStatus: string; medicalDate: string | null; expiryDate: string | null; isReMedical: boolean; contactMedical: boolean; contact: string; contactDoneBy: string; tenFingerDone: boolean; termsDone: boolean; pictureCollected: boolean; medicalSlip: boolean; remark: string; updatedAt: string };
type PageData = { data: MedicalRow[]; filters: { users: Array<{ id: string; name: string }>; offices: Array<{ id: string; name: string }>; statuses: string[]; reportStatuses: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", status: "", reportStatus: "", office: "", updatedFrom: "", updatedTo: "", medicalDate: "", reMedical: "", contactMedical: "", contactDoneBy: "", tenFingerDone: "", termsDone: "", pictureCollected: "", medicalSlip: "" };
const standardStatuses = ["Pending For Medical & Slip", "Submit for Slip", "Pending Medical Present", "Medical Present", "Waiting for Report", "Fit", "Unfit", "Recall", "Medical Done"];
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";
const dateTimeLabel = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export function KsaMedicalPage({ country = "Saudi" }: { country?: string }) {
  const countryLabel = country === "Saudi" ? "Saudi Arabia" : country;
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const query = useQuery({ queryKey: ["ksa-medical", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => { if (value) params.set(key, value); }); const response = await fetch(`/api/ksa/medical?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load medical records"); return response.json() as Promise<PageData>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const dataFilters = query.data?.filters;
  const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const apply = () => { setApplied(filters); setPage(1); }; const clear = () => { setFilters(blank); setApplied(blank); setPage(1); };
  const download = () => { const quote = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const headers = ["SL", "Client", "Candidate No", "Phone", "Passport", "Officer", "Profession", "Status", "Report Status", "Medical Date", "Expire Date", "Contact Medical", "Contact", "Ten Finger", "Terms Done", "Picture", "Medical Slip", "Office", "Company", "Remark", "Last Saved"]; const csv = [headers.join(","), ...rows.map((row, index) => [index + 1, row.name, row.candidateNo, row.phone, row.passportNumber, row.officerName, row.profession, row.status, row.reportStatus, dateLabel(row.medicalDate), dateLabel(row.expiryDate), row.contactMedical ? "YES" : "NO", row.contact, row.tenFingerDone ? "YES" : "NO", row.termsDone ? "YES" : "NO", row.pictureCollected ? "YES" : "NO", row.medicalSlip ? "YES" : "NO", row.office, row.company, row.remark, dateTimeLabel(row.updatedAt)].map(quote).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "saudi-medical-list.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const users = dataFilters?.users ?? []; const statuses = [...new Set([...standardStatuses, ...(dataFilters?.statuses ?? [])])]; const reportStatuses = [...new Set(["Waiting For Report", "Fit", "Unfit", "Recall", ...(dataFilters?.reportStatuses ?? [])])];

  return <div className="ksa-medical-page">
    <header className="ksa-medical-head"><div className="breadcrumb">Dashboard / {countryLabel} Medical Submit</div><h1>{countryLabel} Medical Submit</h1></header>
    <section className="ksa-medical-card">
      <div className="ksa-medical-filters">
        <SearchField label="Passport Number" value={filters.passport} placeholder="Passport number..." onChange={(value) => set("passport", value)} accent />
        <SearchField label="Client Name" value={filters.name} placeholder="Client Name..." onChange={(value) => set("name", value)} />
        <SearchField label="Phone Number" value={filters.phone} placeholder="Phone number..." onChange={(value) => set("phone", value)} />
        <SelectField label="Officer" value={filters.officer} placeholder="Select Officer" options={users.map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => set("officer", value)} />
        <SelectField label="Medical Status" value={filters.status} placeholder="Select Medical Status" options={statuses.map(option)} onChange={(value) => set("status", value)} />
        <SelectField label="Medical Report Status" value={filters.reportStatus} placeholder="Select Medical Report Status" options={reportStatuses.map(option)} onChange={(value) => set("reportStatus", value)} />
        <SelectField label="Office" value={filters.office} placeholder="Select Office" options={(dataFilters?.offices ?? []).map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => set("office", value)} />
        <label className="date-range">Last Updated At Date Range<div><input type="date" aria-label="Last updated from" value={filters.updatedFrom} onChange={(event) => set("updatedFrom", event.target.value)} /><input type="date" aria-label="Last updated to" value={filters.updatedTo} onChange={(event) => set("updatedTo", event.target.value)} /></div></label>
        <label>Medical Date<input type="date" value={filters.medicalDate} onChange={(event) => set("medicalDate", event.target.value)} /></label>
        <CheckFilter label="Re-Medical Files" checked={filters.reMedical === "Yes"} onChange={(checked) => set("reMedical", checked ? "Yes" : "")} />
        <CheckFilter label="Contact Medical" checked={filters.contactMedical === "Yes"} onChange={(checked) => set("contactMedical", checked ? "Yes" : "")} />
        <SelectField label="Contact Medical Done By" value={filters.contactDoneBy} placeholder="Select Done By" options={users.map((item) => ({ value: item.name, label: item.name }))} onChange={(value) => set("contactDoneBy", value)} />
        <CheckFilter label="Ten Finger Done" checked={filters.tenFingerDone === "Yes"} onChange={(checked) => set("tenFingerDone", checked ? "Yes" : "")} />
        <CheckFilter label="Terms & Conditions Done" checked={filters.termsDone === "Yes"} onChange={(checked) => set("termsDone", checked ? "Yes" : "")} />
        <SelectField label="Picture Collected" value={filters.pictureCollected} placeholder="Select Picture Status" options={yesNo} onChange={(value) => set("pictureCollected", value)} />
        <SelectField label="Medical Slip" value={filters.medicalSlip} placeholder="Select Medical Slip" options={yesNo} onChange={(value) => set("medicalSlip", value)} />
        <div className="ksa-medical-actions"><span>Filter</span><div><button onClick={apply}>Apply</button><button onClick={clear}>Clear</button></div></div>
      </div>
      {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Saudi medical records could not be loaded.</div>}
      <div className="ksa-medical-toolbar"><span>Showing <b>{meta.total ? (meta.page - 1) * meta.pageSize + 1 : 0}</b> to <b>{Math.min(meta.page * meta.pageSize, meta.total)}</b> of <b>{meta.total}</b> Results</span><div><select aria-label="Results per page" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }}><option value="10">10</option><option value="20">20</option><option value="50">50</option></select><button onClick={download}><Download size={16} />Download</button></div></div>
      <div className="ksa-medical-table"><table><thead><tr><th>SL</th><th>Actions</th><th>Client information</th><th>Officer</th><th>Profession</th><th>Status</th><th>Report Status</th><th>Medical Date</th><th>Expire Date</th><th>Contact Medical?</th><th>Contact</th><th>Ten Finger Done?</th><th>Terms &amp; Conditions Done?</th><th>Picture Collected?</th><th>Medical Slip?</th><th>Office</th><th>Company</th><th>Remark</th><th>Last Saved</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.medicalId}><td>{(meta.page - 1) * meta.pageSize + index + 1}</td><td><Link href={`/file/${row.id}`}>Actions</Link></td><td className="client-info"><b>{row.name}</b><Link href={`/file/${row.id}`}>{row.candidateNo}</Link><span>{row.phone}</span><small>{row.passportNumber}</small></td><td>{row.officerName}</td><td>{row.profession}</td><td><span className="medical-status">{row.status}</span></td><td>{row.reportStatus}</td><td>{dateLabel(row.medicalDate)}</td><td>{dateLabel(row.expiryDate)}</td><td><BooleanBadge value={row.contactMedical} /></td><td>{row.contactMedical ? row.contact : "N/A"}</td><td><BooleanBadge value={row.tenFingerDone} /></td><td><BooleanBadge value={row.termsDone} /></td><td><BooleanBadge value={row.pictureCollected} /></td><td><BooleanBadge value={row.medicalSlip} /></td><td>{row.office}</td><td>{row.company}</td><td>{row.remark}</td><td>{dateTimeLabel(row.updatedAt)}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={19}>No medical records match these filters.</td></tr>}</tbody></table></div>
      <div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} />Previous</button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}>Next<ChevronRight size={16} /></button></div>
    </section>
  </div>;
}

const yesNo = [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }]; const option = (value: string) => ({ value, label: value });
function SearchField({ label, value, placeholder, onChange, accent = false }: { label: string; value: string; placeholder: string; onChange: (value: string) => void; accent?: boolean }) { return <label className={accent ? "accent" : ""}>{label}<div className="search-input"><Search size={15} /><input value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></div></label>; }
function SelectField({ label, value, placeholder, options, onChange }: { label: string; value: string; placeholder: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">{placeholder}</option>{options.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }
function CheckFilter({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="medical-check"><span>{label}</span><span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />{label}</span></label>; }
function BooleanBadge({ value }: { value: boolean }) { return <span className={`yes-no ${value ? "yes" : "no"}`}>{value ? "YES" : "NO"}</span>; }
