"use client";

import { useQuery } from "@tanstack/react-query";
import { BarChart3, ChevronLeft, ChevronRight, Download, Filter, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type PassportRow = { id: string; fileNo: string; fromInterview: boolean; entryDate: string; candidateNo: string; name: string; phone: string; age: number | null; passportNumber: string; passportExpiry: string | null; officerId: string; officerName: string; agentName: string; office: string; company: string; profession: string; mainStatuses: string[] };
type FilterOptions = { officers: Array<{ id: string; name: string }>; professions: string[]; districts: string[]; agents: string[]; mainStatuses: string[]; medicalStatuses: string[]; medicalReportStatuses: string[]; mofaStatuses: string[]; takamulStatuses: string[]; takamulReportStatuses: string[]; takamulDoneBy: string[]; bioStatuses: string[]; visaStatuses: string[]; manpowerStatuses: string[] };
type PassportPageData = { data: PassportRow[]; filters: FilterOptions; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const emptyFilters = { passport:"",name:"",phone:"",district:"",officer:"",agent:"",mainStatus:"",medicalStatus:"",medicalReportStatus:"",medicalExpireFrom:"",medicalExpireTo:"",mofaStatus:"",mofaNumber:"",takamulStatus:"",takamulReportStatus:"",takamulDoneBy:"",bioStatus:"",bioOfficeStatus:"",bioOffice:"",takamulCertificate:"",certificateOfficeStatus:"",certificateOffice:"",firstPayment:"",secondPayment:"",visaStatus:"",visaDoneFrom:"",visaDoneTo:"",manpowerStatus:"",expireFile:"",entryDate:"",entryFrom:"",entryTo:"",flightFrom:"",flightTo:"",medicalFitPayment:"",visaDonePayment:"",fitCardUpdate:"",fitCardStatus:"",fitCardOfficeStatus:"",paymentMin:"",paymentMax:"",ageMin:"",ageMax:"",contactMedical:"",contactMedicalDoneBy:"",pictureCollected:"",medicalSlip:"",excludeHold:"",excludeReturn:"",fromInterview:"",fitCardOffice:"",passportLocation:"",passportPurpose:"",profession:"" };
type Filters = typeof emptyFilters;
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—";

export function KsaPassportPage({ mode, country = "Saudi" }: { mode: "all" | "entry"; country?: string }) {
  const countryLabel = country === "Saudi" ? "Saudi Arabia" : country;
  const [filters, setFilters] = useState(emptyFilters); const [applied, setApplied] = useState(emptyFilters); const [filtersOpen, setFiltersOpen] = useState(mode === "entry"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const query = useQuery({ queryKey: ["ksa-passports", country, mode, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, mode, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => { if (value) params.set(key, value); }); const response = await fetch(`/api/ksa/passports?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load Saudi passport records"); return response.json() as Promise<PassportPageData>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 };
  const apply = () => { setApplied(filters); setPage(1); }; const clear = () => { setFilters(emptyFilters); setApplied(emptyFilters); setPage(1); };
  const downloadCsv = () => { const esc = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = ["SL,From Interview,Entry Date,Client,Candidate No,Phone,Age,Passport,Passport Expiry,Officer,Agent,Office,Company,Profession,Main Status", ...rows.map((row, index) => [index + 1, row.fromInterview ? "YES" : "NO", dateLabel(row.entryDate), row.name, row.candidateNo, row.phone, row.age ?? "", row.passportNumber, dateLabel(row.passportExpiry), row.officerName, row.agentName, row.office, row.company, row.profession, row.mainStatuses.join(" | ")].map(esc).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = mode === "all" ? "ksa-passport-list.csv" : "ksa-passport-entry-list.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="ksa-passport-page">
    <div className="ksa-passport-head"><div><div className="breadcrumb">Dashboard / {mode === "all" ? "All Passport List" : `${countryLabel} Passport Entry List`}</div><h1>{mode === "all" ? "All Passport List" : `${countryLabel} Passport Entry List`}</h1></div>{mode === "all" && <div className="ksa-report-actions"><Link href={`/module/reports/ksa-total-events-report?country=${encodeURIComponent(country)}`}><BarChart3 size={17} />{country === "Saudi" ? "KSA" : countryLabel} Total Events Report</Link><Link href={`/module/reports/saudi-daily-report?country=${encodeURIComponent(country)}`}><BarChart3 size={17} />{countryLabel} Daily Events Report</Link></div>}</div>
    <section className="ksa-passport-card">
      {mode === "all" && <button className="filter-toggle" onClick={() => setFiltersOpen(!filtersOpen)}><Filter size={16} />Show/Hide Filters</button>}
      {filtersOpen && (mode === "all" ? <AdvancedFilters filters={filters} setFilters={setFilters} options={query.data?.filters} apply={apply} clear={clear} download={downloadCsv} /> : <EntryFilters filters={filters} setFilters={setFilters} options={query.data?.filters} apply={apply} clear={clear} />)}
      {query.isFetching && <><div className="loading-line" /><p className="passport-loading">Loading results...</p></>}{query.isError && <div className="form-error">Passport records could not be loaded.</div>}
      <div className="ksa-table-toolbar"><span>Showing <b>{meta.total ? (meta.page - 1) * meta.pageSize + 1 : 0}</b> to <b>{Math.min(meta.page * meta.pageSize, meta.total)}</b> of <b>{meta.total}</b> Results</span><div><label>Per Page<select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }}><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></label><button onClick={downloadCsv}><Download size={16} />Download CSV</button></div></div>
      <div className="ksa-passport-table"><table><thead><tr><th>SL</th><th><input type="checkbox" aria-label="Select all" /></th>{mode === "entry" && <th>Actions</th>}<th>From Interview</th>{mode === "entry" ? <><th>Entry Date</th><th>Client information</th><th>Passport</th><th>Expire Date</th><th>Officer Name</th><th>Agent Name</th><th>Office</th><th>Company</th><th>Profession Category</th></> : <th>Main Status</th>}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id}><td>{(meta.page - 1) * meta.pageSize + index + 1}</td><td><input type="checkbox" aria-label={`Select ${row.name}`} /></td>{mode === "entry" && <td><Link className="passport-action" href={`/file/${row.id}`}>Actions</Link></td>}<td><span className={`yes-no ${row.fromInterview ? "yes" : "no"}`}>{row.fromInterview ? "YES" : "NO"}</span></td>{mode === "entry" ? <><td>{dateLabel(row.entryDate)}</td><td className="client-info"><b>{row.name}</b><Link href={`/file/${row.id}`}>{row.candidateNo}</Link><span>Phone: {row.phone}</span><span>Age: {row.age ?? "N/A"} Years</span></td><td>{row.passportNumber}</td><td>{dateLabel(row.passportExpiry)}</td><td>{row.officerName}</td><td>{row.agentName}</td><td>{row.office}</td><td>{row.company}</td><td>{row.profession}</td></> : <td><div className="main-statuses">{row.mainStatuses.map((status) => <span className={statusTone(status)} key={status}>{status}</span>)}</div></td>}</tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={mode === "entry" ? 13 : 4}>No passport records match these filters.</td></tr>}</tbody></table></div>
      <div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} />Previous</button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}>Next<ChevronRight size={16} /></button></div>
    </section>
  </div>;
}

const yn = [{value:"Yes",label:"Yes"},{value:"No",label:"No"}];
const strOpts = (items: string[] = []) => items.map(value=>({value,label:value}));
type FilterProps = { filters: Filters; setFilters: (value: Filters) => void; options?: FilterOptions; apply:()=>void; clear:()=>void };
function EntryFilters({filters,setFilters,options,apply,clear}:FilterProps){ const set=(key:keyof Filters,value:string)=>setFilters({...filters,[key]:value}); return <div className="ksa-passport-filters"><SearchField label="Passport Number" value={filters.passport} placeholder="Passport number..." onChange={v=>set("passport",v)} accent/><SearchField label="Client Name" value={filters.name} placeholder="Client Name..." onChange={v=>set("name",v)}/><SearchField label="Phone Number" value={filters.phone} placeholder="Phone number..." onChange={v=>set("phone",v)}/><SelectField label="Officer" value={filters.officer} placeholder="Select Officer" options={(options?.officers??[]).map(x=>({value:x.id,label:x.name}))} onChange={v=>set("officer",v)}/><DateField label="Entry Date" value={filters.entryDate} onChange={v=>set("entryDate",v)}/><SelectField label="Profession Category" value={filters.profession} placeholder="Select Profession Category" options={strOpts(options?.professions)} onChange={v=>set("profession",v)}/><SelectField label="From Interview" value={filters.fromInterview} placeholder="Select From Interview" options={yn} onChange={v=>set("fromInterview",v)}/><FilterActions apply={apply} clear={clear}/></div> }
function AdvancedFilters({filters,setFilters,options,apply,clear,download}:FilterProps&{download:()=>void}){ const set=(key:keyof Filters,value:string)=>setFilters({...filters,[key]:value}); const select=(label:string,key:keyof Filters,items=yn,placeholder="Select option")=><SelectField key={key} label={label} value={filters[key]} placeholder={placeholder==="Select option"?"Select "+label:placeholder} options={items} onChange={v=>set(key,v)}/>; return <div className="ksa-passport-filters advanced">
  <SearchField label="Passport Number" value={filters.passport} placeholder="Passport number..." onChange={v=>set("passport",v)} accent/><SearchField label="Name" value={filters.name} placeholder="Name" onChange={v=>set("name",v)}/><SearchField label="Phone Number" value={filters.phone} placeholder="Phone number" onChange={v=>set("phone",v)}/>
  {select("Present District","district",strOpts(options?.districts))}{select("Officer","officer",(options?.officers??[]).map(x=>({value:x.id,label:x.name})))}{select("Agent","agent",strOpts(options?.agents))}{select("Main Status","mainStatus",strOpts(options?.mainStatuses))}
  {select("Medical Status","medicalStatus",strOpts(options?.medicalStatuses))}{select("Medical Report Status","medicalReportStatus",strOpts(options?.medicalReportStatuses))}<DatePair label="Medical Expire Date" from={filters.medicalExpireFrom} to={filters.medicalExpireTo} setFrom={v=>set("medicalExpireFrom",v)} setTo={v=>set("medicalExpireTo",v)}/>
  {select("MOFA Status","mofaStatus",strOpts(options?.mofaStatuses))}<SearchField label="MOFA Number" value={filters.mofaNumber} placeholder="Enter MOFA Number" onChange={v=>set("mofaNumber",v)}/>{select("Takamul Status","takamulStatus",strOpts(options?.takamulStatuses))}{select("Takamul Report Status","takamulReportStatus",strOpts(options?.takamulReportStatuses))}{select("Takamul Done By","takamulDoneBy",strOpts(options?.takamulDoneBy))}
  {select("KSA Bio Status","bioStatus",strOpts(options?.bioStatuses))}{select("KSA Bio Finger Office Status","bioOfficeStatus")}{select("KSA Bio Finger Office","bioOffice")}{select("Takamul Certificate","takamulCertificate")}{select("Takamul Certificate Office Status","certificateOfficeStatus")}{select("Takamul Certificate Office","certificateOffice")}
  {select("First Payment (50k)","firstPayment")}{select("Second Payment (150k)","secondPayment")}{select("Visa Status","visaStatus",strOpts(options?.visaStatuses))}<DatePair label="Visa Done Date" from={filters.visaDoneFrom} to={filters.visaDoneTo} setFrom={v=>set("visaDoneFrom",v)} setTo={v=>set("visaDoneTo",v)}/>{select("Manpower Status","manpowerStatus",strOpts(options?.manpowerStatuses))}
  {select("Expire File","expireFile")}<DatePair label="Entry Date" from={filters.entryFrom} to={filters.entryTo} setFrom={v=>set("entryFrom",v)} setTo={v=>set("entryTo",v)}/><DatePair label="Flight Date" from={filters.flightFrom} to={filters.flightTo} setFrom={v=>set("flightFrom",v)} setTo={v=>set("flightTo",v)}/>{select("Medical Fit & First Payment (50k)","medicalFitPayment")}{select("Visa Done + Second Payment (150k)","visaDonePayment")}
  {select("Medical Fit Card Update","fitCardUpdate")}{select("Fit Card Status","fitCardStatus")}{select("Fit Card Office Status","fitCardOfficeStatus")}<RangeField label="Payment Range (From – To)" from={filters.paymentMin} to={filters.paymentMax} setFrom={v=>set("paymentMin",v)} setTo={v=>set("paymentMax",v)}/><RangeField label="Age Range (From – To)" from={filters.ageMin} to={filters.ageMax} setFrom={v=>set("ageMin",v)} setTo={v=>set("ageMax",v)}/>
  {select("Contact Medical","contactMedical")}{select("Contact Medical Done By","contactMedicalDoneBy")}{select("Picture Collected","pictureCollected")}{select("Medical Slip","medicalSlip")}<CheckField label="Exclude Hold File" checked={!!filters.excludeHold} onChange={v=>set("excludeHold",v?"Yes":"")}/><CheckField label="Exclude Return File" checked={!!filters.excludeReturn} onChange={v=>set("excludeReturn",v?"Yes":"")}/>{select("From Interview","fromInterview")}{select("Fit Card Office","fitCardOffice")}{select("Passport manage location","passportLocation")}{select("Passport manage purpose","passportPurpose")}
  <div className="advanced-filter-footer"><FilterActions apply={apply} clear={clear}/><button className="advanced-download" onClick={download}><Download size={16}/>Download</button></div>
 </div> }
function DateField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label>{label}<input type="date" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function DatePair({label,from,to,setFrom,setTo}:{label:string;from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void}){return <label className="range-field">{label}<span><input aria-label={label+" from"} type="date" value={from} onChange={e=>setFrom(e.target.value)}/><i>–</i><input aria-label={label+" to"} type="date" value={to} onChange={e=>setTo(e.target.value)}/></span></label>}
function RangeField({label,from,to,setFrom,setTo}:{label:string;from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void}){return <label className="range-field">{label}<span><input type="number" placeholder="From" value={from} onChange={e=>setFrom(e.target.value)}/><i>–</i><input type="number" placeholder="To" value={to} onChange={e=>setTo(e.target.value)}/></span></label>}
function CheckField({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="check-field">{label}<span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label.replace("Exclude","Except")}</span></label>}
function FilterActions({apply,clear}:{apply:()=>void;clear:()=>void}){return <div className="ksa-filter-actions"><span>Filter</span><div><button type="button" onClick={apply}>Apply</button><button type="button" onClick={clear}>Clear</button></div></div>}
function SearchField({ label, value, placeholder, onChange, accent = false }: { label: string; value: string; placeholder: string; onChange: (value: string) => void; accent?: boolean }) { return <label className={accent ? "accent" : ""}>{label}<div><Search size={15} /><input value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></div></label>; }
function SelectField({ label, value, placeholder, options, onChange }: { label: string; value: string; placeholder: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">{placeholder}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function statusTone(status: string) { return /hold|return/i.test(status) ? "rose" : /payment/i.test(status) ? "yellow" : /medical/i.test(status) ? "blue" : /takamul|bio/i.test(status) ? "purple" : "green"; }
