"use client";

import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Row = { id: string; paymentId: string; fileNo: string; candidateNo: string; name: string; phone: string; passportNumber: string; officerId: string; officer: string; office: string; company: string; profession: string; visaStatus: string; visaNumber: string; visaExpiry: string | null; visaDone: boolean; paymentStatus: string; amount: number; paidAmount: number; balance: number; currency: string; dueDate: string | null; collectedAt: string | null; collector: string };
type Data = { data: Row[]; filters: { users: Array<{ id: string; name: string }>; visaStatuses: string[]; paymentStatuses: string[] }; meta: { page: number; pageSize: number; total: number; totalPages: number } };
const blank = { passport: "", name: "", phone: "", officer: "", expiryFrom: "", expiryTo: "", visaStatus: "", completion: "", paymentStatus: "", amountFrom: "", amountTo: "", excludeExpired: "" };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "N/A";

export function KsaSecondPaymentPage({ country = "Saudi", title = "Pending 2nd Payment" }: { country?: string; title?: string }) {
  const [filters, setFilters] = useState(blank); const [applied, setApplied] = useState(blank); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const query = useQuery({ queryKey: ["ksa-second-payment", country, applied, page, pageSize], queryFn: async () => { const params = new URLSearchParams({ country, page: String(page), pageSize: String(pageSize) }); Object.entries(applied).forEach(([key, value]) => value && params.set(key, value)); const response = await fetch(`/api/ksa/second-payment?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error("Could not load second payment records"); return response.json() as Promise<Data>; } });
  const rows = query.data?.data ?? []; const meta = query.data?.meta ?? { page, pageSize, total: 0, totalPages: 1 }; const choices = query.data?.filters; const set = (key: keyof typeof blank, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const download = () => { const q = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const lines = [["SL", "Client", "Candidate", "Phone", "Passport", "Visa Status", "Visa Expiry", "Payment Status", "Total", "Paid", "Balance", "Currency", "Due Date", "Officer", "Office", "Company"].join(","), ...rows.map((row, index) => [index + 1, row.name, row.candidateNo, row.phone, row.passportNumber, row.visaStatus, dateLabel(row.visaExpiry), row.paymentStatus, row.amount, row.paidAmount, row.balance, row.currency, dateLabel(row.dueDate), row.officer, row.office, row.company].map(q).join(","))]; const url = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "pending-second-payment.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="ksa-second-payment-page"><header><div className="breadcrumb">Dashboard / {title}</div><h1>{title}</h1></header><section className="second-payment-card"><div className="second-payment-filters"><Field label="Passport Number"><input className="accent" placeholder="Passport number..." value={filters.passport} onChange={(e) => set("passport", e.target.value)} /></Field><Field label="Client Name"><input placeholder="Client name..." value={filters.name} onChange={(e) => set("name", e.target.value)} /></Field><Field label="Phone Number"><input placeholder="Phone number..." value={filters.phone} onChange={(e) => set("phone", e.target.value)} /></Field><Field label="Officer"><Select placeholder="Select Officer" value={filters.officer} options={(choices?.users ?? []).map((x) => [x.id, x.name])} onChange={(v) => set("officer", v)} /></Field><Field label="Visa Expire Date Range"><DateRange from={filters.expiryFrom} to={filters.expiryTo} onFrom={(v) => set("expiryFrom", v)} onTo={(v) => set("expiryTo", v)} /></Field><Field label="Visa Status"><Select placeholder="All" value={filters.visaStatus} options={(choices?.visaStatuses ?? []).map(asOption)} onChange={(v) => set("visaStatus", v)} /></Field><Field label="Visa Done & Second Payment"><Select placeholder="All" value={filters.completion} options={["Both Done", "Visa Done", "Second Payment Done", "Pending"].map(asOption)} onChange={(v) => set("completion", v)} /></Field><Field label="Second Payment"><Select placeholder="All" value={filters.paymentStatus} options={["PENDING", "DUE", "PARTIAL", "PAID", "OVERDUE", ...(choices?.paymentStatuses ?? [])].filter(unique).map(asOption)} onChange={(v) => set("paymentStatus", v)} /></Field><Field label="Paid Amount (From - To)"><div className="amount-range"><input type="number" placeholder="From" value={filters.amountFrom} onChange={(e) => set("amountFrom", e.target.value)} /><span>–</span><input type="number" placeholder="To" value={filters.amountTo} onChange={(e) => set("amountTo", e.target.value)} /></div></Field><label className="second-check"><input type="checkbox" checked={filters.excludeExpired === "Yes"} onChange={(e) => set("excludeExpired", e.target.checked ? "Yes" : "")} /><span>Exclude expired visa</span></label><div className="second-actions"><button onClick={() => { setApplied(filters); setPage(1); }}>Apply</button><button onClick={() => { setFilters(blank); setApplied(blank); setPage(1); }}>Clear</button></div></div>
    {query.isFetching && <div className="loading-line" />}{query.isError && <div className="form-error">Second payment records could not be loaded.</div>}<div className="second-toolbar"><button onClick={download}><Download size={16} />Download</button><div><span>Showing <b>{meta.total ? (page - 1) * pageSize + 1 : 0}</b> of <b>{meta.total}</b> Results</span><select value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}><option>10</option><option>20</option><option>50</option></select></div></div><div className="second-payment-table"><table><thead><tr><th>SL.</th><th>Actions</th><th>Client Info</th><th>Visa Status</th><th>Visa Number</th><th>Visa Expiry</th><th>Second Payment</th><th>Total Amount</th><th>Paid Amount</th><th>Balance</th><th>Due Date</th><th>Collected</th><th>Officer</th><th>Office</th><th>Profession</th><th>Company</th><th>Collector</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.paymentId}><td>{(page - 1) * pageSize + index + 1}</td><td><Link href={`/file/${row.id}`}>Actions</Link></td><td className="client-info"><b>{row.name}</b><Link href={`/file/${row.id}`}>{row.candidateNo}</Link><span>{row.phone}</span><small>{row.passportNumber}</small></td><td><span className={`second-badge ${row.visaDone ? "done" : ""}`}>{row.visaStatus}</span></td><td>{row.visaNumber}</td><td>{dateLabel(row.visaExpiry)}</td><td><span className={`second-badge ${row.paymentStatus === "PAID" ? "done" : ""}`}>{row.paymentStatus}</span></td><td>{row.amount.toLocaleString()} {row.currency}</td><td>{row.paidAmount.toLocaleString()}</td><td>{row.balance.toLocaleString()}</td><td>{dateLabel(row.dueDate)}</td><td>{dateLabel(row.collectedAt)}</td><td>{row.officer}</td><td>{row.office}</td><td>{row.profession}</td><td>{row.company}</td><td>{row.collector}</td></tr>)}{!rows.length && !query.isFetching && <tr><td className="table-empty" colSpan={17}>No data available in table</td></tr>}</tbody></table></div><div className="ksa-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>{page}</b><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div>
  </section></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span>{label}</span>{children}</label>; }
function Select({ placeholder, value, options, onChange }: { placeholder: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <select value={value} onChange={(e) => onChange(e.target.value)}><option value="">{placeholder}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>; }
function DateRange({ from, to, onFrom, onTo }: { from: string; to: string; onFrom: (value: string) => void; onTo: (value: string) => void }) { return <div className="second-date-range"><input aria-label="Visa expiry from" type="date" value={from} onChange={(e) => onFrom(e.target.value)} /><input aria-label="Visa expiry to" type="date" value={to} onChange={(e) => onTo(e.target.value)} /></div>; }
function asOption(value: string) { return [value, value]; }
function unique(value: string, index: number, array: string[]) { return array.indexOf(value) === index; }
