import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";
import { workflowCountryWhere, workflowModule } from "@/lib/workflow-country";

type UploadRow = { fileNo?: string; candidateNo?: string; passportNumber?: string; status?: string; fitCardStatus?: string; visaNumber?: string; visaType?: string; profession?: string; submissionDate?: string; issueDate?: string; stampingDate?: string; expiryDate?: string };
type MedicalMeta = { fitCardStatus?: string };
const day = (value: string, last = false) => value ? new Date(`${value}T${last ? "23:59:59.999" : "00:00:00"}`) : null;
const within = (value: string | null, from: string, to: string) => (!from || Boolean(value && new Date(value) >= day(from)!)) && (!to || Boolean(value && new Date(value) <= day(to, true)!));
const asDate = (value?: string) => value ? new Date(value) : null;

export async function GET(request: Request) {
  try {
const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, workflowModule(request), "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403);
    const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim(); const page = Math.max(1, Number(p("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(p("pageSize")) || 20));
const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: workflowCountryWhere(request), visas: { some: {} } }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, visas: { take: 1, orderBy: { createdAt: "desc" } }, medical: { take: 1, orderBy: { createdAt: "desc" } } } });
    const rows = files.flatMap((file) => { const visa = file.visas[0]; if (!visa) return []; const medical = file.medical[0]; const meta = medical?.metadata && typeof medical.metadata === "object" ? medical.metadata as MedicalMeta : {}; const dob = file.candidate.dob; const age = dob ? Math.max(0, Math.floor((Date.now() - dob.getTime()) / 31557600000)) : null; return [{ id: file.id, visaId: visa.id, fileNo: file.fileNo, candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, age, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", officerId: file.assignedTo?.id ?? "", officerName: file.assignedTo?.name ?? "Unassigned", officeId: file.office?.id ?? "", office: file.office?.name ?? "SELF", company: file.company ?? "N/A", status: visa.status, fitCardStatus: meta.fitCardStatus ?? (medical?.result?.toLowerCase().includes("fit") ? "Done" : "Pending"), visaNumber: visa.visaNumber ?? "N/A", visaType: visa.visaType ?? "N/A", profession: visa.profession ?? file.profession ?? file.candidate.profession ?? "N/A", submissionDate: visa.submissionDate?.toISOString() ?? null, issueDate: visa.issueDate?.toISOString() ?? null, stampingDate: visa.stampingDate?.toISOString() ?? null, expiryDate: visa.expiryDate?.toISOString() ?? null, document: visa.visaObjectKey ?? "N/A" }]; });
    const filtered = rows.filter((r) => (!p("passport") || r.passportNumber.toLowerCase().includes(p("passport").toLowerCase())) && (!p("name") || r.name.toLowerCase().includes(p("name").toLowerCase())) && (!p("phone") || r.phone.toLowerCase().includes(p("phone").toLowerCase())) && (!p("officer") || r.officerId === p("officer")) && (!p("office") || r.officeId === p("office")) && (!p("status") || r.status === p("status")) && (!p("fitCardStatus") || r.fitCardStatus === p("fitCardStatus")) && (!p("profession") || r.profession === p("profession")) && within(r.submissionDate, p("submitFrom"), p("submitTo")) && within(r.issueDate, p("issueFrom"), p("issueTo")) && within(r.expiryDate, p("expiryFrom"), p("expiryTo")));
    const [users, offices] = await Promise.all([prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.office.findMany({ where: { status: "ACTIVE", ...(session.user.officeId ? { id: session.user.officeId } : {}) }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const values = (key: "status" | "fitCardStatus" | "profession") => [...new Set(rows.map((r) => r[key]).filter(Boolean))].sort(); const offset = (page - 1) * pageSize;
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, offices, statuses: values("status"), fitCardStatuses: values("fitCardStatus"), professions: values("profession") }, meta: { page, pageSize, total: filtered.length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}

export async function POST(request: Request) {
  try {
    const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, "ksa", "Create"))) throw new AppError("FORBIDDEN", "Create permission is required.", 403); const body = await request.json() as { rows?: UploadRow[] }; const rows = body.rows ?? []; if (!rows.length || rows.length > 500) throw new AppError("INVALID_CSV", "CSV must contain between 1 and 500 rows.", 422); let imported = 0; const errors: string[] = [];
    for (const [index, row] of rows.entries()) { const identifier = row.fileNo || row.candidateNo || row.passportNumber; if (!identifier) { errors.push(`Row ${index + 2}: identifier is required.`); continue; } const file = await prisma.processingFile.findFirst({ where: { ...officeScope(session), country: workflowCountryWhere(request), OR: [{ fileNo: identifier }, { candidate: { candidateNo: identifier } }, { passport: { passportNumber: identifier } }] } }); if (!file) { errors.push(`Row ${index + 2}: file not found for ${identifier}.`); continue; } try { await prisma.visaProcess.create({ data: { fileId: file.id, status: row.status || "Submitted", visaNumber: row.visaNumber || null, visaType: row.visaType || null, profession: row.profession || null, submissionDate: asDate(row.submissionDate), issueDate: asDate(row.issueDate), stampingDate: asDate(row.stampingDate), expiryDate: asDate(row.expiryDate) } }); imported++; } catch { errors.push(`Row ${index + 2}: visa record could not be imported.`); } }
    return Response.json({ data: { imported, errors } }, { status: imported ? 201 : 422 });
  } catch (error) { return errorResponse(error); }
}
