import { can, officeScope } from "@/lib/authorization";
import { AppError, errorResponse } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/session";
import { workflowCountryWhere, workflowModule } from "@/lib/workflow-country";

type Meta = { isReMedical?: boolean };
const meta = (value: unknown): Meta => value && typeof value === "object" ? value as Meta : {};

export async function GET(request: Request) {
  try {
const session = await getSession(); if (!session) throw new AppError("UNAUTHORIZED", "Sign in is required.", 401); if (!(await can(session, workflowModule(request), "View"))) throw new AppError("FORBIDDEN", "View permission is required.", 403); const url = new URL(request.url); const p = (key: string) => (url.searchParams.get(key) ?? "").trim().toLowerCase(); const page = Math.max(1, Number(url.searchParams.get("page")) || 1); const pageSize = Math.min(100, Math.max(10, Number(url.searchParams.get("pageSize")) || 20));
    const files = await prisma.processingFile.findMany({ where: { ...officeScope(session), country: workflowCountryWhere(request), currentStage: new URL(request.url).searchParams.get("stage") || "Pre Confirm File" }, orderBy: { updatedAt: "desc" }, take: 5000, include: { candidate: true, passport: true, assignedTo: { select: { id: true, name: true } }, office: { select: { id: true, name: true } }, payments: { where: { type: "First Payment" }, take: 1, orderBy: { createdAt: "desc" } }, medical: { take: 1, orderBy: { createdAt: "desc" } }, mofa: { take: 1, orderBy: { createdAt: "desc" } }, takamul: { take: 1, orderBy: { createdAt: "desc" } }, biometrics: { where: { type: "KSA Bio Finger" }, take: 1, orderBy: { createdAt: "desc" } }, police: { take: 1, orderBy: { createdAt: "desc" } } } });
    const rows = files.map((file) => { const medical = file.medical[0], mofa = file.mofa[0]; return { id: file.id, fileNo: file.fileNo, candidateNo: file.candidate.candidateNo, name: file.candidate.fullName, phone: file.candidate.phone, passportNumber: file.passport?.passportNumber ?? file.candidate.passportNo ?? "Not entered", country: file.country, officerId: file.assignedTo?.id ?? "", officer: file.assignedTo?.name ?? "Unassigned", officeId: file.office?.id ?? "", office: file.office?.name ?? "SELF", company: file.company ?? "N/A", profession: file.profession ?? file.candidate.profession ?? "N/A", status: file.status, paymentStatus: file.payments[0]?.status ?? "PENDING", medicalStatus: medical?.result ?? "Pending", mofaStatus: mofa?.status ?? "Pending", takamulStatus: file.takamul[0]?.reportStatus || file.takamul[0]?.status || "Pending", bioStatus: file.biometrics[0]?.status ?? "Pending", policeStatus: file.police[0]?.status ?? "Pending", reMedical: Boolean(medical?.isReMedical || meta(mofa?.metadata).isReMedical), reMofa: Boolean(mofa?.isReMofa), updatedAt: file.updatedAt.toISOString() }; });
    const filtered = rows.filter((row) => (!p("passport") || row.passportNumber.toLowerCase().includes(p("passport"))) && (!p("name") || row.name.toLowerCase().includes(p("name"))) && (!p("phone") || row.phone.toLowerCase().includes(p("phone"))) && (!p("officer") || row.officerId.toLowerCase() === p("officer")) && (!p("office") || row.officeId.toLowerCase() === p("office")) && (!p("paymentStatus") || row.paymentStatus.toLowerCase() === p("paymentStatus"))); const [users, offices] = await Promise.all([prisma.user.findMany({ where: { ...officeScope(session), status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.office.findMany({ where: { status: "ACTIVE", ...(session.user.officeId ? { id: session.user.officeId } : {}) }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); const offset = (page - 1) * pageSize;
    return Response.json({ data: filtered.slice(offset, offset + pageSize), filters: { users, offices }, meta: { page, pageSize, total: filtered.length, totalPages: Math.max(1, Math.ceil(filtered.length / pageSize)) } });
  } catch (error) { return errorResponse(error); }
}
